### ISSUE TITLE
exception caught by gesture

### ISSUE THREAD

**Issue by uzairpawaskar** [TheAlphamerc/flutter_twitter_clone#10]
The following assertion was thrown while handling a gesture:
Tried to listen to a value exposed with provider, from outside of the widget tree.

This is likely caused by an event handler (like a button's onPressed) that called
Provider.of without passing `listen: false`.

To fix, write:
Provider.of<AuthState>(context, listen: false);

It is unsupported because may pointlessly rebuild the widget associated to the
event handler, when the widget tree doesn't care about the value.

The context used was: WelcomePage(dependencies: [MediaQuery, _DefaultInheritedProviderScope<AuthState>], state: _WelcomePageState#7b321)
'package:provider/src/provider.dart':
Failed assertion: line 193 pos 7: 'context.owner.debugBuilding || listen == false || _debugIsInInheritedProviderUpdate'

**Comment by uzairpawaskar** [comment]
can i get a solution to this?

**Comment by TheAlphamerc** [comment]
Please take a fresh clone of the repository and check if you still face such an error.

**Comment by uzairpawaskar** [comment]
i tried with the new repository.. even tired to change the flutter channel, after i change the flutter channel to dev. provider issues was gone by that but now i am facing other issue with this..

Error: The getter 'isInitialRoute' isn't defined for the class 'RouteSettings'.
 - 'RouteSettings' is from 'package:flutter/src/widgets/navigator.dart' ('/C:/flutter/packages/flutter/lib/src/widgets/navigator.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'isInitialRoute'.
    if (settings.isInitialRoute) { 

please bare with me i am a newbie in flutter

**Comment by TheAlphamerc** [comment]
Run following command on terminal 
``` dart 
flutter clean
flutter pub get
```

**Comment by uzairpawaskar** [comment]
still not solved.. same issue.. i read the documentation of provider.. the file is updates that's why the code is showing error

**Comment by TheAlphamerc** [comment]
> i tried with the new repository.. even tired to change the flutter channel, after i change the flutter channel to dev. provider issues was gone by that but now i am facing other issue with this..
> 
> Error: The getter 'isInitialRoute' isn't defined for the class 'RouteSettings'.
> 
> * 'RouteSettings' is from 'package:flutter/src/widgets/navigator.dart' ('/C:/flutter/packages/flutter/lib/src/widgets/navigator.dart').
>   Try correcting the name to the name of an existing getter, or defining a getter or field named 'isInitialRoute'.
>   if (settings.isInitialRoute) {
> 
> please bare with me i am a newbie in flutter

Revert back to flutter stable channel and run above command.

**Comment by uzairpawaskar** [comment]
i tried that too its not working

**Comment by TheAlphamerc** [comment]
Please share screenshot of error and code where you think the issue is occurring.

**Comment by uzairpawaskar** [comment]
google services file is missing
i cannot add mine because different package name

**Comment by TheAlphamerc** [comment]
<img width="1318" alt="Screenshot 2020-04-15 at 10 41 12 PM" src="https://user-images.githubusercontent.com/37103237/79367099-e694e500-7f6a-11ea-9ccc-d1772caad5c9.png">

Follow below steps to update package name
* Go to  /android/app/build.gradle 
* Replace application "com.thealphamerc.flutter_twitter_clone" by your package name.

**Comment by uzairpawaskar** [comment]
the application starts.. when i click on the button it give me the error i mentioned in the start.. screen stuck there

**Comment by TheAlphamerc** [comment]
This error occures when you clicked on heart ❤️ button ?

**Comment by uzairpawaskar** [comment]
no.. its not even letting me create any account or to sign in.. just stuck on the first page

**Comment by uzairpawaskar** [comment]
package:provider/src/provider.dart':
Failed assertion: line 193 pos 7: 'context.owner.debugBuilding || listen == false || _debugIsInInheritedProviderUpdate'

this is the error that i get when i click on any button

**Comment by uzairpawaskar** [comment]
i think the issue is caused because of different versions of provider library.. where determining 4.0.2 will solve the issue but that works on "dev" channel.. shifting to dev channel creates a lot of different errors

**Comment by TheAlphamerc** [comment]
I am using Flutter 1.12.13+hotfix.8 • channel stable and its working fine.

**Comment by TheAlphamerc** [comment]
Add below provider version in pubspec.yml
`provider: ^3.2.0`

Please check https://github.com/TheAlphamerc/flutter_twitter_clone/issues/24#issuecomment-623464462
