### ISSUE TITLE
creating dialog with a list of names on signup screen

### ISSUE THREAD

**Issue by karambitmonger** [TheAlphamerc/flutter_twitter_clone#100]
Hi there,me again LOL..sucks bein a flutter noob..
I want to add a field for profession while signing up. How do i tap the edit text box and pop up dialog with professions where one selects and it sets the text in the edit text box?

**Comment by TheAlphamerc** [comment]
Use text field inside the container wrapped with GestureDector and use ontap function to display a dialog.
Inside dialog add a list of professions with the help of RadioTiles. Add a submit button below tiles to select the profession and close the dialog.
