### ISSUE TITLE
Want to get all tweet to homepage

### ISSUE THREAD

**Issue by biwiwijaya** [TheAlphamerc/flutter_twitter_clone#103]
I got the best app for learning reference, thank you...😭👍

But i wanna ask about, how i can show all tweets to homepage?

Is this state have to delete? Or how?
Pls help me😭👍

/// Only include Tweets of logged-in user's and his following user's
        if (x.user.userId == userModel.userId ||
            (userModel?.followingList != null &&
                userModel.followingList.contains(x.user.userId))) {
          return true;
        } else {
          return false;
        }
      }).toList();
      if (list.isEmpty) {
        list = null;
      }
    }
    return list;
  }

**Comment by TheAlphamerc** [comment]
Do you want to display all user's tweets on the home page? Then what's the use of `Follow` feature?

**Comment by biwiwijaya** [comment]
I mean, I want create one page for discover page..

**Comment by biwiwijaya** [comment]
And show all the tweets

**Comment by TheAlphamerc** [comment]
To display all tweets update `getTweetList ` function with below code.

```dart
 /// contain tweet list for home page
  List<FeedModel> getTweetList(User userModel) {
    if (userModel == null) {
      return null;
    }
 return feedlist;
  }

```

**Comment by biwiwijaya** [comment]
Thankyou, i will try it👍😭
