### ISSUE TITLE
Firebase User Deprecated.

### ISSUE THREAD

**Issue by uzairpawaskar** [TheAlphamerc/flutter_twitter_clone#106]
I was trying to migrate this project in android v2.0 
Ran into some Firebase issues like:

1) error: The getter 'isEmailVerified' isn't defined for the type 'FirebaseUser'. 

2)error: Undefined name 'GoogleAuthProvider'. (undefined_identifier at [flutter_twitter_clone] lib\state\authState.dart:111)

3)error: Undefined class 'AuthCredential'. (undefined_class at [flutter_twitter_clone] lib\state\authState.dart:111)

4)error: The method 'signInWithCredential' isn't defined for the type 'FirebaseAuth'. (undefined_method at [flutter_twitter_clone] lib\state\authState.dart:115)

5)error: The getter 'creationTime' isn't defined for the type 'FirebaseUserMetadata'. (undefined_getter at [flutter_twitter_clone] lib\state\authState.dart:142)

6)error: The getter 'lastSignInTime' isn't defined for the type 'FirebaseUserMetadata'. (undefined_getter at [flutter_twitter_clone] lib\state\authState.dart:161)

7)error: The getter 'user' isn't defined for the type 'FirebaseUser'. (undefined_getter at [flutter_twitter_clone] lib\state\authState.dart:174)

8)error: The getter 'user' isn't defined for the type 'FirebaseUser'. (undefined_getter at [flutter_twitter_clone] lib\state\authState.dart:180)

9)error: Undefined class 'StorageReference'. (undefined_class at [flutter_twitter_clone] lib\state\authState.dart:305)

10)error: Undefined class 'StorageUploadTask'. (undefined_class at [flutter_twitter_clone] lib\state\authState.dart:308)

11)error: Undefined class 'StorageReference'. (undefined_class at [flutter_twitter_clone] lib\state\feedState.dart:338)

12)error: Undefined class 'StorageUploadTask'. (undefined_class at [flutter_twitter_clone] lib\state\feedState.dart:341)

13)error: Undefined class 'StorageReference'. (undefined_class at [flutter_twitter_clone] lib\state\feedState.dart:366)

I believe this is happening because Firebase has made some changes.. Can u help me in this???
would really appericiate.

**Comment by TheAlphamerc** [comment]
@uzairpawaskar These issues will get resolve soon I have started the work on migration project to android v2.0 and new version of firebase package.

**Comment by TheAlphamerc** [comment]
@uzairpawaskar Issue is fixed.

**Comment by uzairpawaskar** [comment]
Thanks for a fast and good response.. really appreciate your work..
