### ISSUE TITLE
I facing error after adding code for update user Across everywhere

### ISSUE THREAD

**Issue by emiravdovic** [TheAlphamerc/flutter_twitter_clone#107]
after I Add code for update user across everywhere I facing error every time when I run app, first showing reed screen with this message..

![Screenshot 2020-11-07 at 18 40 10](https://user-images.githubusercontent.com/53181006/98447985-577b3480-2129-11eb-900c-bd4fa2c9a86a.png)

and after this showing list of posts...

![Screenshot 2020-11-07 at 18 38 15](https://user-images.githubusercontent.com/53181006/98448002-6eba2200-2129-11eb-9d03-f80c3a30b396.png)

But when I hide this code app running normal..

**Comment by TheAlphamerc** [comment]
@emiravdovic take a pull and check if you still facing the same issue.

**Comment by emiravdovic** [comment]
I using version with firestore database. will this update work there also bc some of code don't exist in "firestore" version app..

**Comment by TheAlphamerc** [comment]
I have upgraded master and firestore branch so don't worry about that.

**Comment by emiravdovic** [comment]
@TheAlphamerc I still have same problem when user run app when is across Everywhere function allowed, but when is // Closed then dont have error but user dont updating, what to do?

**Comment by emiravdovic** [comment]
@TheAlphamerc  if I add this betwen code `if (searchState.userList.isNotEmpty)` ,   dont have this error but images dont updating..

**Comment by TheAlphamerc** [comment]
@emiravdovic I am not sure how much you have modified the code but I am sure about the original code it is working fine.
