### ISSUE TITLE
Got Error while release apk

### ISSUE THREAD

**Issue by biwiwijaya** [TheAlphamerc/flutter_twitter_clone#109]
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.14.3\android\build.gradle' line: 54

* What went wrong:
A problem occurred evaluating project ':cloud_firestore'.
> Could not find method platform() for arguments [com.google.firebase:firebase-bom:25.12.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                       1.7s
Gradle task assembleRelease failed with exit code 1

**Comment by biwiwijaya** [comment]
![error2](https://user-images.githubusercontent.com/73777248/98642434-629ab400-2325-11eb-897f-ef63e706d3e5.jpg)

**Comment by TheAlphamerc** [comment]
@biwiwijaya take a pull from the repository, run build `flutter clean` command try building again.
