### ISSUE TITLE
Splash Screen error after last update

### ISSUE THREAD

**Issue by emiravdovic** [TheAlphamerc/flutter_twitter_clone#110]
after update code to last update, I having reed screen when I run app 
![Screenshot 2020-11-10 at 14 24 21](https://user-images.githubusercontent.com/53181006/98679716-b5459180-2360-11eb-82cf-540abf86524c.png)
![Screenshot 2020-11-10 at 14 25 08](https://user-images.githubusercontent.com/53181006/98679736-bd053600-2360-11eb-8d2c-2a12a83ecf2a.png)

**Comment by TheAlphamerc** [comment]
On which branch you are working?

**Comment by emiravdovic** [comment]
@TheAlphamerc  I using version with firestore

**Comment by TheAlphamerc** [comment]
Did you have the latest code pull?

**Comment by emiravdovic** [comment]
@TheAlphamerc  I upgrade app every time when new update is available..

**Comment by TheAlphamerc** [comment]
Try `flutter clean` command and run again. I just checked the code and it is running fine.

**Comment by emiravdovic** [comment]
@TheAlphamerc  I will try now, is possible that problem make "dependencies" version in "pub spec"?

**Comment by emiravdovic** [comment]
@TheAlphamerc Still same problem..

**Comment by TheAlphamerc** [comment]
Replace `SplacePage()` with `SignIn()` in Route class.

<img width="583" alt="Screenshot 2020-11-11 at 10 10 25 AM" src="https://user-images.githubusercontent.com/37103237/98769497-3440d580-2406-11eb-9616-e755981cf220.png">

**Comment by emiravdovic** [comment]
@TheAlphamerc Now working properly, problem was that I missed some code, and after I check code and founded where was missing part, working properly.. 💯
