### ISSUE TITLE
Images Not Showing Up On The Timeline

### ISSUE THREAD

**Issue by mowet601** [TheAlphamerc/flutter_twitter_clone#111]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**App**
- version[e.g.  1.0.4]

**Additional context**

**Comment by biwiwijaya** [comment]
when i compose tweet with image, feed page only showing a loading screen
 
Device : Pixel 4 API 30
OS : Android 11.0
Version : x86

**Comment by TheAlphamerc** [comment]
@mowet601 @biwiwijaya Please check if you have the latest code on your system and  if yes then please mention the branch name on which you are working.

**Comment by biwiwijaya** [comment]
i just fresh pull with default code from the lastest update fwitter and cannot upload image also..

**Comment by TheAlphamerc** [comment]
@mowet601 @biwiwijaya The issue is fixed. Please let me know if you still face the issue.
