### ISSUE TITLE
Got error when compose tweet

### ISSUE THREAD

**Issue by biwiwijaya** [TheAlphamerc/flutter_twitter_clone#112]
when i compose a tweet with image, feedpage only showing a loading screen..

D/skia    ( 7479): Shader compilation error
D/skia    ( 7479): ------------------------
D/skia    ( 7479): Errors:
D/skia    ( 7479):
W/IInputConnectionWrapper( 7479): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 7479): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper( 7479): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper( 7479): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 7479): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 7479): endBatchEdit on inactive InputConnection
D/skia    ( 7479): Shader compilation error
D/skia    ( 7479): ------------------------
D/skia    ( 7479): Errors:
D/skia    ( 7479):
D/skia    ( 7479): Shader compilation error
D/skia    ( 7479): ------------------------
D/skia    ( 7479): Errors:

**Comment by TheAlphamerc** [comment]
@biwiwijaya  Issue is resolved. See https://github.com/TheAlphamerc/flutter_twitter_clone/issues/111 for details.
