### ISSUE TITLE
Push notification not working

### ISSUE THREAD

**Issue by karambitmonger** [TheAlphamerc/flutter_twitter_clone#113]
Hi,i have tried everything and i am unable to get notifications when someone,reacts to a post or any other interaction on the app.
I have followed the steps at wiki section numerous times and i am still unable to get notifications. I have tried reading up and viewing other tutotrials but still nothing. In the terminal i can see 'notification' added and 'notification removed 'but no notification on the device.

Please please help me as i have tried everything else but no solution.

**Comment by TheAlphamerc** [comment]
The notifications that you on the console like notification added or removed is not actually push notification. They are in app notification and can be viewed on notification screen.
Push notification will be sent to you if someone tagged you in tweet or send you a message. Please make sure that you have added Push notification server key at firebase remote config in correct format.

**Comment by karambitmonger** [comment]
i have done it the exact way at wiki,could you show me how that format looks?

**Comment by TheAlphamerc** [comment]
<img width="924" alt="Screenshot 2020-11-12 at 6 33 17 PM" src="https://user-images.githubusercontent.com/37103237/98947405-2b8df380-251b-11eb-93c3-6ce5e413d275.png">

**Comment by karambitmonger** [comment]
Hey sonu! i decided to create push notification functions and deploy them to firebase the old fashioned way. I can get notifications now when someone likes a comment. WOuld you assist me with some code that can allow me to open the notification page once the notification in notification tray is clicked?

**Comment by TheAlphamerc** [comment]
The feature is implemented in the project so I'm closing the issue.
