### ISSUE TITLE
Want to different page between post and post detail

### ISSUE THREAD

**Issue by dyingwell123** [TheAlphamerc/flutter_twitter_clone#114]
This is cool apk for learning flutter🙏

I wanna ask question, if i wanna separate page between post with post detail, where the code should be change?
I hope you will tell me about this, thank you, sir🙏

**Comment by TheAlphamerc** [comment]
@dyingwell123 I didn't understand your question. Can you explain it in detail?

**Comment by biwiwijaya** [comment]
in feed page and in the detail page, the post looks like the same body, how can i change it?
i wanna to change it with different body..

**Comment by TheAlphamerc** [comment]
To change tweet body design modify the code available in `Tweet` Widget.

<img width="963" alt="Screenshot 2020-11-13 at 12 25 44 PM" src="https://user-images.githubusercontent.com/37103237/99038430-8111e100-25ab-11eb-9db9-57c8134d3ae7.png">
