### ISSUE TITLE
Adding parameter in Wiki page

### ISSUE THREAD

**Issue by mcuadrai** [TheAlphamerc/flutter_twitter_clone#115]
** Description**
   As a rookie, it took me hours to find why I couldn't sign up with a Google account.
   I thought it wasn't important the message: Please add your app's current version into Remote config in firebase,
      and log .. Latest version of app is not installed on your system ...

**Solution**
    I created a parameter appVersion in Remote Config in Firebase, using json format, with content : {"key":"1.0.6"}
    and  recommend put this information in Wiki page.       

**Alternatives**
   Another alternative is to write the default setting inside of code and not put the information on the Wiki page.

**Comment by TheAlphamerc** [comment]
@mcuadrai I don't know why you aren't able to signup using Google. Firebase remote config for app version has nothing to do with google login. If somehow you forgot to add remote config in firebase it won't stop you to login in development mode. It just shows you a message on the console.
Also, I didn't notice earlier that I haven't added this info in Wiki. Thanks for letting me know, I will add it.
