### ISSUE TITLE
Upload more than 1 image

### ISSUE THREAD

**Issue by biwiwijaya** [TheAlphamerc/flutter_twitter_clone#117]
Hello, I want to upload more than 1 image, where's the code should be change?, thank you, sir

**Comment by TheAlphamerc** [comment]
You can find this code in `ComposeBottomIconWidget` class.

<img width="1132" alt="Screenshot 2020-11-21 at 10 08 43 PM" src="https://user-images.githubusercontent.com/37103237/99882467-b4590d80-2c46-11eb-8c2d-49e631e62481.png">
