### ISSUE TITLE
Unable to pick and upload image as i changed and upgraded target androidSDK to 29

### ISSUE THREAD

**Issue by karambitmonger** [TheAlphamerc/flutter_twitter_clone#118]
This issue is specific to samsung devices only,as i have tried on other devices and they work. Anybody have a workaround?

**Comment by TheAlphamerc** [comment]
I think this issue is related to [image_picker](https://pub.dev/packages/image_picker) package. Please check if someone else face this issue [here](https://github.com/flutter/flutter/issues)
