### ISSUE TITLE
when text field is clicked, Homepage and text field build again

### ISSUE THREAD

**Issue by devit365** [TheAlphamerc/flutter_twitter_clone#120]
added print method on 2 files to check when it is called.

page/homePage.dart

  @override
  Widget build(BuildContext context) {
    **print('build homepage'); // added this line**
    return Scaffold(
      key: _scaffoldKey,
      bottomNavigationBar: BottomMenubar(),
      drawer: SidebarMenu(),
      body: _body(),
    );
  }

page/feed/composeTweet/composeTweet.dart

class _TextField extends StatelessWidget {
  ...

  @override
  Widget build(BuildContext context) {
    **print('build textfield'); // added this line**
    final searchState = Provider.of<SearchState>(context, listen: false);
   ...

when I click textfield on compose feed page.
it prints as below.

"build homepage"
"build textfield"

I don't want to print "build homepage"

Could you please check it?

Thank you.

**Comment by TheAlphamerc** [comment]
On compose tweet screen there and some listeners called and those are very much needed and cause home page to rebuild when `notifierlistener()` function called.

**Comment by devit365** [comment]
Thank you for your reply.
Is it possible to fix this issue.
Because I want to show admob full banner when main page is initialized.
But when I click textfield, admob full banner shows again.
And when I submit the compose page, main page runs again. and admob full banner is showing again.

**Comment by TheAlphamerc** [comment]
I think you are invoking the method from the build method that's why it is displaying again. Use init method to display admob banner.
