### ISSUE TITLE
Change email, password and username

### ISSUE THREAD

**Issue by qwerty684** [TheAlphamerc/flutter_twitter_clone#123]
how to make that user can change email password and username?

**Comment by TheAlphamerc** [comment]
Check this  https://github.com/TheAlphamerc/flutter_twitter_clone/issues/62#issuecomment-661062636

**Comment by qwerty684** [comment]
@TheAlphamerc  okay I made now that user add custom username, but I how to navigate user to page where user will add username, when user create account over google?

**Comment by TheAlphamerc** [comment]
It doesn't matter if user created account using signup or google. A unique username is assigned to each user and saved into a database. You can provide an option in the edit profile to update the username.

**Comment by qwerty684** [comment]
yes this, but I trying to create username over google also, and I want to navigate user to page where the will put username after then signup with. google..
