### ISSUE TITLE
Creating Realtime Database Admin Users

### ISSUE THREAD

**Issue by mowet601** [TheAlphamerc/flutter_twitter_clone#124]
What would be the easiest way to add Admin Users to the Realtime Database?

**Comment by TheAlphamerc** [comment]
First of all, there is no shortcut or easiest way to create an admin user and secondly, this project is a clone to Twitter and I don't think Twitter has some kind of Admin user.

**Comment by mowet601** [comment]
I understand. I am trying to moderate the posts by being able to delete inappropriate posts as the admin i feel like i'm close to the solution i'm looking for.  
![Screen Shot 2021-02-12 at 2 07 23 PM](https://user-images.githubusercontent.com/4493458/107811139-b5787300-6d3b-11eb-8b17-5d6eb8b2dda4.png)

**Comment by TheAlphamerc** [comment]
Assign a admin role to a user account and save it to database. Put check condition while deleting the tweet. If user role is admin then allow user to delete it.
