### ISSUE TITLE
Has anyone tried to deploy this as a flutter web project successfully

### ISSUE THREAD

**Issue by karambitmonger** [TheAlphamerc/flutter_twitter_clone#126]
I have tried to deploy on web but i am stuck on splash screen

**Comment by TheAlphamerc** [comment]
I'm not sure of it cuz I didn't tried it.

**Comment by TheAlphamerc** [comment]
As far as I know  @DovAzencot has deployed it on web. Check details here -> https://github.com/TheAlphamerc/flutter_twitter_clone/issues/127
