### ISSUE TITLE
additional interesting clones

### ISSUE THREAD

**Issue by twepl** [TheAlphamerc/flutter_twitter_clone#128]
I have collected some interesting forks that may come in handy in development
1 https://github.com/FerVillanuevas/flutter-tweet
2 https://github.com/iamabhishek229313/flutter_twitter
3 https://github.com/Hardikkr/Twitter_Clone

**Comment by TheAlphamerc** [comment]
Thanks @twepl

**Comment by twepl** [comment]
@TheAlphamerc 
https://github.com/Ali-hd/Twitter-Clone
https://github.com/Ali-hd/TwitterClone-Backend

**Comment by twepl** [comment]
@TheAlphamerc https://github.com/conghaonet/GitHao
