### ISSUE TITLE
my app is slowing down

### ISSUE THREAD

**Issue by twepl** [TheAlphamerc/flutter_twitter_clone#129]
My app is working weird, I can't figure it out because of flutter or my phone is not working well.
for example if you download the official twitter app it works faster than the flutter app.
do you have the same thing or is it just me?

**Comment by TheAlphamerc** [comment]
I never face this issue. App works faster all time no matter if it is development build on release one.

**Comment by twepl** [comment]
try to compare with this app
https://play.google.com/store/apps/details?id=com.twitter.android&hl=ru&gl=US
