### ISSUE TITLE
code to redirect me to the comments(FeedPostDetail page) page when i click on push notification

### ISSUE THREAD

**Issue by karambitmonger** [TheAlphamerc/flutter_twitter_clone#131]
Hi @TheAlphamerc i have managed to create a cloud function that triggers a push notification when a user like or comments on  a tweet. can you help me with code that can navigate me to the post when when i click on the push notification

**Comment by TheAlphamerc** [comment]
There is a `onLaunch` callback in  `inItFirebaseService` method. Whenever user tap on notification this callback triggers so you can navigate from here to detail screen.

![Untitled](https://user-images.githubusercontent.com/37103237/105273717-d973e900-5bc1-11eb-948b-a497da88bb31.png)
