### ISSUE TITLE
Google Sign up emailVerified = true / to false by default

### ISSUE THREAD

**Issue by qwerty684** [TheAlphamerc/flutter_twitter_clone#132]
How to remove Verified badge from users who create account over google, by default giving to them that the have Verified badge...

![Screenshot 2021-01-21 at 00 33 09](https://user-images.githubusercontent.com/53181006/105253844-947b9280-5b80-11eb-8aea-412a3ba0e7f8.png)

**Comment by TheAlphamerc** [comment]
In `createUserFromGoogleSignIn()` method assign false to `IsVerified`

![Untitled](https://user-images.githubusercontent.com/37103237/105273188-cca2c580-5bc0-11eb-9357-a670fddb3cbb.png)

**Comment by qwerty684** [comment]
@TheAlphamerc  When I mark to false, to database it says it's false, but when I open the profile page, the badge is visible, and also sidebar stay badge, other user are not able to seen it, just me..

**Comment by qwerty684** [comment]
@TheAlphamerc  Right now even if I set false from database, after user open profile page or some other, this automatically change to true alone, and like this is only when user create account over google, but with normal signup working properly..

**Comment by TheAlphamerc** [comment]
In authstate class there is function `getProfileUser()` which checks if user's email is verifies or not. To restrict this comment down reload `reloadUser()` function.
![Untitled](https://user-images.githubusercontent.com/37103237/105572377-cb1dfc80-5d7c-11eb-8468-4c06941d6bef.png)

**Comment by qwerty684** [comment]
@TheAlphamerc When user "A" create account over google in database stay that user "A" is not verified, but when I look to profile page, or to sidebar menu, there still stay that is verified..
And when I come  with other account  to this user "A" to check if is verified, user "A" is not verified..
