### ISSUE TITLE
application slows down

### ISSUE THREAD

**Issue by ghost** [TheAlphamerc/flutter_twitter_clone#137]
I already wrote that the application slows down, can you optimize the code to make it work more efficiently?

**Comment by TheAlphamerc** [comment]
@twepl can you specify how the application is slows down? Is this issue persist in whole app or in any specific section?

**Comment by twepl** [comment]
> @twepl can you specify how the application is slows down? Is this issue persist in whole app or in any specific section?

slows down during transitions from page to page.
as if there is not enough memory, or something else.

**Comment by TheAlphamerc** [comment]
@twepl I have tested the development and release build as well but didn't face this issue. Can you share the build here so that I can  check it ?

**Comment by twepl** [comment]
@TheAlphamerc I apologize now I'm very busy there is no time to start, I have already deleted the old version.
