### ISSUE TITLE
can't run app

### ISSUE THREAD

**Issue by harounsk** [TheAlphamerc/flutter_twitter_clone#139]
Launching lib\main.dart on RNE L21 in debug mode...
lib\main.dart:1
Checking the license for package Android SDK Platform 29 in C:\Users\Haroun\AppData\Local\Android\sdk\licenses
License for package Android SDK Platform 29 accepted.
Preparing "Install Android SDK Platform 29 (revision: 5)".
"Install Android SDK Platform 29 (revision: 5)" ready.
Installing Android SDK Platform 29 in C:\Users\Haroun\AppData\Local\Android\sdk\platforms\android-29
"Install Android SDK Platform 29 (revision: 5)" complete.
"Install Android SDK Platform 29 (revision: 5)" finished.
Note: C:\Flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.5.2\android\src\main\java\io\flutter\plugins\firebase\core\FlutterFirebaseCorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.14.3\android\src\main\java\io\flutter\plugins\firebase\firestore\FlutterFirebaseFirestorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Flutter\.pub-cache\hosted\pub.dartlang.org\firebase_analytics-6.2.0\android\src\main\java\io\flutter\plugins\firebaseanalytics\FirebaseAnalyticsPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.18.3\android\src\main\java\io\flutter\plugins\firebase\auth\FlutterFirebaseAuthPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Flutter\.pub-cache\hosted\pub.dartlang.org\firebase_database-4.3.0\android\src\main\java\io\flutter\plugins\firebase\database\FirebaseDatabasePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
C:\Flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage-5.0.1\android\src\main\java\io\flutter\plugins\firebase\storage\FlutterFirebaseStoragePlugin.java:38: warning: [deprecation] Registrar in PluginRegistry has been deprecated
  public static void registerWith(PluginRegistry.Registrar registrar) {
                                                ^
1 warning
Note: C:\Flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in-4.5.6\android\src\main\java\io\flutter\plugins\googlesignin\GoogleSignInPlugin.java uses or overrides a deprecated API.

**Comment by TheAlphamerc** [comment]
@harounsk  run `flutter clean build` command and try to compile build again. I don't see any issue on this logs.

**Comment by harounsk** [comment]
> @harounsk run `flutter clean build` command and try to compile build again. I don't see any issue on this logs.

I tried but nothing. Same error
do I need to configure firebase before build???

**Comment by jonathangull** [comment]
@harounsk yes you need to configure firebase, as stated in  - https://github.com/TheAlphamerc/flutter_twitter_clone/wiki/Gettings-Started 
I just setup the project and it worked just fine.  @TheAlphamerc Great Job.
