### ISSUE TITLE
isInitialRoute removal at beta channel and will come to stable channel soon.

### ISSUE THREAD

**Issue by guyulmaz** [TheAlphamerc/flutter_twitter_clone#14]
**Describe the bug**

https://flutter.dev/docs/release/breaking-changes/route-navigator-refactoring

https://github.com/flutter/flutter/issues/51649

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by botdesk** [comment]
I have the same issue : b/helper/customRoute.dart:14:18: Error: The getter 'isInitialRoute' isn't defined for the class 'RouteSettings'.
 - 'RouteSettings' is from 'package:flutter/src/widgets/navigator.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/navigator.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'isInitialRoute'.
    if (settings.isInitialRoute) {

**Comment by TheAlphamerc** [comment]
Please read this thread:- https://github.com/TheAlphamerc/flutter_twitter_clone/issues/30#issue-613947043
