### ISSUE TITLE
Video feature help implement

### ISSUE THREAD

**Issue by JavierPerezLavadie** [TheAlphamerc/flutter_twitter_clone#140]
Hello thanks for this code, I changed ComposeTweetImage to Composeteetvideo, it works and I also have access to the camera .. Can you tell me how to add the video from the camera to Composeteetvideo please.

I'm not asking you for code, just explain it to me in writing please. Thanks

**Comment by TheAlphamerc** [comment]
Hi @JavierPerezLavadie , Can you tell me which package you are using to access video camera ?

**Comment by JavierPerezLavadie** [comment]
Hello, thanks for your answer, forgot my last question. The fwitter firebase dependencies have many incompatibilities with the 0.8.0 camera version. Do you know how to use the 0.8.0 camera on fwitter? The only version that worked is the camera: ^0.5.8+11. Thanks
