### ISSUE TITLE
On scroll fetch data

### ISSUE THREAD

**Issue by ublockme** [TheAlphamerc/flutter_twitter_clone#144]
Hello brother! Can we add onscroll Pagination? Because internet data consuming more whenever we open app. It will be good for users If we added onscroll load more option.

**Comment by TheAlphamerc** [comment]
Hi @ublockme , Yes you are correct adding pagination will be a good technique in order to reduce internet data consumption. I'll add this in TODO list.

**Comment by ublockme** [comment]
Waiting for it brother 😊
Make it asap if you can

**Comment by ublockme** [comment]
I tired some of scroll pagination. ```Example: https://pub.dev/packages/infinite_scroll_pagination```
But getting lots of error. What's the best way to get scroll pagination? We wanna add it in our app because it's every important to reduce data usage and also it will help users to use app properly without hang. 
Can u guide me bro? or 
Can u make scroll pagination in our app?

**Comment by TheAlphamerc** [comment]
I agree with your statement that pagination can reduce data usage but it can only be possible with firestore database. Firebase realtime database didn't provide that much accessibility to fetch page wise data.

**Comment by ublockme** [comment]
got it bro! thanks
