### ISSUE TITLE
The method 'shareFiles' isn't defined for the type 'Share'

### ISSUE THREAD

**Issue by valentine-sys** [TheAlphamerc/flutter_twitter_clone#147]
https://github.com/TheAlphamerc/flutter_twitter_clone/blob/5dc2e226332bc904765d0022b58ee3823d849c9e/lib/helper/utility.dart#L256

**Comment by TheAlphamerc** [comment]
This method is available in [Share](https://pub.dev/packages/share/versions/2.0.1) package v2.0.1.Please check its documentation.
