### ISSUE TITLE
Hide Retweets on news feed

### ISSUE THREAD

**Issue by ublockme** [TheAlphamerc/flutter_twitter_clone#148]
Hi brother! Can we hide retweets on news feed? 
I got this doubt suddenly because tweet and retweets storing in the same field on firebase database, then how can we hide retweets? We need to separate those on field first right? Or having any other options?

**Comment by TheAlphamerc** [comment]
Hi, Apparently we can hide retweets from feed by not showing post having `parentkey ` variable.

**Comment by ublockme** [comment]
Thank u brother!
