### ISSUE TITLE
Show only verified users tweets on feed page

### ISSUE THREAD

**Issue by ublockme** [TheAlphamerc/flutter_twitter_clone#149]
Hi brother! Hope well!

I just want to change news feed to show only verified users post (no followers post) for discover page. Can you guide me please.

**Comment by TheAlphamerc** [comment]
If you want to display tweets of verified user then check for isVarified value in `model.user.isVarified` value and apply conditions according to it to display tweets.

**Comment by ublockme** [comment]
Like this brother? 👇

`    List<FeedModel> list;

    if (!isBusy && feedlist != null && feedlist.isNotEmpty) {
      list = feedlist.where((x) {
        /// If Tweet is a comment then no need to add it in tweet list
        if (x.parentkey != null &&
            x.childRetwetkey == null &&
            x.user.userId != userModel.userId) {
          return false;
        }

        /// Only include Tweets of logged-in user's and his following user's
        if (x.user.userId == userModel.userId ||
            (userModel?.isVerified != null &&
                userModel.isVerified.contains(x.user.userId))) {
          return true;`

**Comment by TheAlphamerc** [comment]
Try this.

```dart 
if (x.user.userId == userModel.userId || (userModel?.followingList != null
 &&  userModel.followingList.contains(x.user.userId) && x.user.isVerified)) {
      return true;
   } else {
     return false;
  }
```

**Comment by ublockme** [comment]
Ok brother i will but I don't wanna show following tweets so can I remove it like this?

```
if (x.user.userId == userModel.userId || (userModel?.followingList != null
 && x.user.isVerified)) {
      return true;
   } else {
     return false;
  }

```

**Comment by TheAlphamerc** [comment]
If you don't want to see following user's tweets then use below.

```dart
if (x.user.userId == userModel.userId || (userModel?.followingList != null
 &&  !userModel.followingList.contains(x.user.userId) && x.user.isVerified)) {
      return true;
   } else {
     return false;
  }
```

**Comment by ublockme** [comment]
Ok i try and tell u brother.

**Comment by ublockme** [comment]
Only this code working well brother to show only verified users tweet on feed page
```if (x.user.userId == userModel.userId || (x.user.isVerified)) {
      return true;
   } else {
     return false;
  }```

**Comment by TheAlphamerc** [comment]
Yes this code will work but you also will be able to see all users tweets whether you are following them or not.

**Comment by ublockme** [comment]
Yes thats what i need 😜 
Thank u brother 
I close this
