### ISSUE TITLE
Update user-profile across everywhere

### ISSUE THREAD

**Issue by algokun** [TheAlphamerc/flutter_twitter_clone#15]
**Describe the bug**
We need to update the user profile information in all the posts he uploaded.

We normally denormalise the data when it comes to NoSQL Databases.

**Comment by TheAlphamerc** [comment]
Yes, I agree with your suggestion and will definitely work on it.

**Comment by TheAlphamerc** [comment]
Issue is resolved please check here:- https://github.com/TheAlphamerc/flutter_twitter_clone/issues/80#issuecomment-672572634
