### ISSUE TITLE
Biggist bug is update user profile

### ISSUE THREAD

**Issue by a-l-iak** [TheAlphamerc/flutter_twitter_clone#150]
After following some user; if you update your profile, your followers and the following list is resetting.

Problemlem is here " kDatabase.child('profile').child(user.userID).set(user.toJson()); "

**Comment by TheAlphamerc** [comment]
Hi @a-l-iak this bug is already fixed. Check https://github.com/TheAlphamerc/flutter_twitter_clone/issues/143

**Comment by a-l-iak** [comment]
thanks
