### ISSUE TITLE
Flutter launcher icons not working

### ISSUE THREAD

**Issue by ublockme** [TheAlphamerc/flutter_twitter_clone#153]
Brother kindly add ```flutter_launcher_icons: ^0.7.3``` dependencies and also ```flutter_icons: android:"lanucher_icon"``` in pubspec.yaml

Because now launcher icon not working.

**Comment by TheAlphamerc** [comment]
What do you mean by Launcher icon not working ? I don't understand how it suppose to work?

**Comment by ublockme** [comment]
![Launcher icon](https://user-images.githubusercontent.com/79246685/115960051-e390e500-a52c-11eb-9f4d-bd277a19c455.jpg)

**Comment by TheAlphamerc** [comment]
So I guess you want to change this icon right ?

**Comment by TheAlphamerc** [comment]
> Brother kindly add `flutter_launcher_icons: ^0.7.3` dependencies and also `flutter_icons: android:"lanucher_icon"` in pubspec.yaml
> 
> Because now launcher icon not working.

flutter_launcher_icon package is already there in pubspec.yml please check. https://github.com/TheAlphamerc/flutter_twitter_clone/blob/5dc2e226332bc904765d0022b58ee3823d849c9e/pubspec.yaml#L60

**Comment by ublockme** [comment]
You already added fwitter icon in pubspec.yaml dependencies right? But only counter default icon showing here even you added fwitter icon.. 
![Launcher icon](https://user-images.githubusercontent.com/79246685/115960221-cad4ff00-a52d-11eb-94ec-a6bdb17e8c5e.jpg)

So we need to add ``` flutter_icons: android:"true" ``` to ``` flutter_icons: android:"lanucher_icon" ```

Even you added ``` flutter_launcher_icons: "^0.7.3"  ``` it will not work brother..

**Comment by TheAlphamerc** [comment]
Default icon is showing because I didn't mean to use any other icon for app. If you want to change this icon you can check the documentation of [flutter_launcher_icons](https://pub.dev/packages/flutter_launcher_icons) package. You will find how to set icon image path for android and a command `flutter pub get
flutter pub run flutter_launcher_icons:main` to generate icons.

**Comment by ublockme** [comment]
Oh ok brother! Thank u so much 😊
