### ISSUE TITLE
Not showing any tweets from varios users on homepage

### ISSUE THREAD

**Issue by davidjrokello** [TheAlphamerc/flutter_twitter_clone#154]
I have tried switching different accounts to check whether i can get tweets from the users who logged in but i dont see the tweets, ca someone help me please.
I havent changed a single code yet

**Comment by TheAlphamerc** [comment]
Hi @davidjrokello , In order to see tweets of other user you need to follow those users.

**Comment by TheAlphamerc** [comment]
> I have tried switching different accounts to check whether i can get tweets from the users who logged in but i dont see the tweets, ca someone help me please.
> I havent changed a single code yet

Are you saying that you are not able to see your own tweets ?

**Comment by davidjrokello** [comment]
I am able to view my tweets but i canot view other users tweets.
I need to view tweets without following anyone

**Comment by TheAlphamerc** [comment]
This is not how [Twitter](https://twitter.com/) app works. Fwitter is designed to simulate Twitter app but still you wants to see all users post there is a workaround for this.

**Comment by davidjrokello** [comment]
Okay how can i work around this ?

**Comment by TheAlphamerc** [comment]
Replace below code in getTweetList method
https://github.com/TheAlphamerc/flutter_twitter_clone/blob/5dc2e226332bc904765d0022b58ee3823d849c9e/lib/state/feedState.dart#L43

```dart
List<FeedModel> getTweetList(UserModel userModel) {
    if (userModel == null) {
      return null;
    }

    List<FeedModel> list;

    if (!isBusy && feedlist != null && feedlist.isNotEmpty) {
      list = feedlist.where((x) {
        /// If Tweet is a comment then no need to add it in tweet list
        if (x.parentkey != null &&
            x.childRetwetkey == null &&
            x.user.userId != userModel.userId) {
          return false;
        }
      return true;
      }).toList();
      if (list.isEmpty) {
        list = null;
      }
    }
    return list;
  }
```

**Comment by ublockme** [comment]
@davidjrokello and also u can show only verified users (even not followed users tweet) tweets on news feed of u changed 
``` /// Only include Tweets of logged-in user's and his following user's
        if (x.user.userId == userModel.userId ||
            (userModel?.followingList != null &&
                userModel.followingList.contains(x.user.userId))) {
          return true;
        } else {
          return false;
        } ```
to 
``` /// Only include Tweets of logged-in user's and verified users
if (x.user.userId == userModel.userId || (x.user.isVerified)) {
      return true;
   } else {
     return false;
  } ```
in feedstate.dart page

**Comment by davidjrokello** [comment]
Thanks, I'll check it out.

**Comment by davidjrokello** [comment]
Hello,
Hope this finds you well, I am trying to add another description like
random location in my tweet, i have specified it in FeedModel and also
added another textfield which will contain another text.
I am trying but it has taken alot of time, this is where you come in.
I need your help

**Comment by TheAlphamerc** [comment]
Are you trying to let user enter the location info in a tweet while composing a new one ?
