### ISSUE TITLE
AppIcon problem

### ISSUE THREAD

**Issue by gulmensedat** [TheAlphamerc/flutter_twitter_clone#16]
AppIcons are not visible. What would be the reason?

**Comment by ajatsoft** [comment]
Have it in assets

**Comment by gulmensedat** [comment]
> Have it in assets

fonts:
    - family: TwitterIcon
      fonts:
        - asset: assets/fonts/icons.ttf
okey..

**Comment by TheAlphamerc** [comment]
<img width="331" alt="Screenshot 2020-04-20 at 9 13 47 AM" src="https://user-images.githubusercontent.com/37103237/79712117-a5446280-82e7-11ea-9431-4df34de946a6.png">
You can find it at 
Project folder > assets > images

**Comment by gulmensedat** [comment]
> <img alt="Screenshot 2020-04-20 at 9 13 47 AM" width="331" src="https://user-images.githubusercontent.com/37103237/79712117-a5446280-82e7-11ea-9431-4df34de946a6.png">
> 
> You can find it at Project folder > assets > images

I mentioned all the icons. I learned it in the above answer.
Thanks.
