### ISSUE TITLE
Getting error When open tweet details

### ISSUE THREAD

**Issue by ublockme** [TheAlphamerc/flutter_twitter_clone#163]
Hello brother! I updated app code recently. After that, getting error while open tweet details when I debug on emulator. 

App was perfectly run before I update circular image code but now getting error. How to solve it? I tired many but I can't solve it 😐

![Error image](https://user-images.githubusercontent.com/79246685/117391868-7e66c780-af0e-11eb-82e8-3a9729985e26.jpeg)

**Comment by TheAlphamerc** [comment]
@ublockme Issue is fixed. Thanks for letting me about this.

**Comment by ublockme** [comment]
😀 i tired to add width in tweet.dart but I forgot to remove context in extention.dart 
Thanks brother
