### ISSUE TITLE
Add Stories 

### ISSUE THREAD

**Issue by aylasnavegador** [TheAlphamerc/flutter_twitter_clone#164]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by TheAlphamerc** [comment]
@aylasnavegador I didn't understand what you are trying to say. Please add some descriptive details.

**Comment by aylasnavegador** [comment]
add Stories, it’s great if you have Stories and also post videos

**Comment by TheAlphamerc** [comment]
Currently adding stories and video post is not in priority list but surely can be included in future.
