### ISSUE TITLE
The getter 'retweetCount' was called on null.

### ISSUE THREAD

**Issue by ublockme** [TheAlphamerc/flutter_twitter_clone#165]
Is this issue only for me? 
I don't know but I wanna let you know it.

Getting error  ```The getter 'retweetCount' was called on null.``` like this when I retweet. 
How to solve it?

**Comment by TheAlphamerc** [comment]
@ublockme how you got this issue ? is this issue still persist in code or you did something wrong and got this issue ?

**Comment by ublockme** [comment]
Nothing i did but i got this sudden issue. I also checked fire base field. Retweet count added there correctly but in emulator i got error like getter retweetcount was called on null. Surely I know i did nothing in retweet dart code so i simply clean pub and deleted build folder and rebuild the code. Now its working properly.
