### ISSUE TITLE
Great job

### ISSUE THREAD

**Issue by drstewen** [TheAlphamerc/flutter_twitter_clone#166]
Thanks bro to share this awesome app. Really great job.
I just want to  learn , if i download and run in any IDE without editing, can i use cloud firestore as default or should i change codes?

**Comment by ublockme** [comment]
Yeah he done great job! Ok i share my knowledge before he reply. 
You can't use cloud firestore without editing. Because he updated codes in master branch. Master branch runs in real time database so you can't use cloud branch code without editing. 

Am i right @TheAlphamerc

**Comment by TheAlphamerc** [comment]
@ublockme You are right about it. In master branch I have implemented firebase_realtime database. @drstewen If you want to use cloud firestore then switch to `firestore_db` branch. In If you checkout `firestore_db` branch you will find the cloud firestore implementation.

**Comment by drstewen** [comment]
Thanks for answers
