### ISSUE TITLE
Cant Load image

### ISSUE THREAD

**Issue by drstewen** [TheAlphamerc/flutter_twitter_clone#168]
In cloud firestore branch , i can see internet images in virtual emulator. When i build apk images can not  load in phsical device.

Despite of I already add internet permission into manifest

Edit: i also can not get notification, i did all implements

**Comment by TheAlphamerc** [comment]
@drstewen I have checked and it is working fine on emulator as well as physical device.

**Comment by TheAlphamerc** [comment]
For notification make sure you have added FCM Server key in remote config.

**Comment by drstewen** [comment]
![Screenshot_2021-05-13-01-36-11-759_com.jetmeet.jetmeeting.jpg](https://user-images.githubusercontent.com/79838424/118052574-aa110400-b38b-11eb-91fc-f5ac4dbcb784.jpg)

Still like that, i changed all tree shake icons because before i change i could not build any apk file. Now i can but like that.

By the way, i am sure to save fcmKey properly. İ can see logs once send and recieve message and any like  update but never see notification.

Can someone help me about this?

**Comment by TheAlphamerc** [comment]
Can you share image URL of image which you have posrted in Tweet ?

**Comment by drstewen** [comment]
https://firebasestorage.googleapis.com/v0/b/jetmeeting-28cb2.appspot.com/o/tweetImage%2Fscaled_15906625-5ec8-4d50-a56f-2ba6ae7aa3a08980068136977847866.jpg?alt=media&token=4f1a446e-eec2-464b-8c88-9e7f831327fd

**Comment by TheAlphamerc** [comment]
@drstewen  I have used same url in app and it is working fine.

![Screenshot_2021-05-13-17-25-28-901_com.thealphamerc.flutter_twitter_clone_dev.jpg](https://user-images.githubusercontent.com/37103237/118122533-9e1b5580-b410-11eb-93ee-6c9a5ca10d44.jpg)

**Comment by drstewen** [comment]
@TheAlphamerc thanks for your interest, do you know how can i fix it? It is the first time i have ever seen a problem like that.

**Comment by TheAlphamerc** [comment]
Do you have latest code from `firestore` branch ?

**Comment by drstewen** [comment]
I downloaded the code as zip file 1 week ago

**Comment by TheAlphamerc** [comment]
Have you change something in code ?

**Comment by drstewen** [comment]
As i wrote before  at first i could not build apk because of tree shake icons. I removed them from the codes.

**Comment by TheAlphamerc** [comment]
Did you change code in `customNetworkImage` or `customAdvanceNetworkImage` widget ?

<img width="1293" alt="Screenshot 2021-05-13 at 6 12 46 PM" src="https://user-images.githubusercontent.com/37103237/118127172-38967d00-b3ae-11eb-8964-7eab9a76a743.png">

**Comment by drstewen** [comment]
I dont remember i will check it again soon and  will reply

**Comment by drstewen** [comment]
@TheAlphamerc  no change here
![image](https://user-images.githubusercontent.com/79838424/118129268-9fdf1c00-b404-11eb-9595-be151b04004d.png)

**Comment by TheAlphamerc** [comment]
It's weird, No one faces this issue before. Not sure why this is occurred to you.

**Comment by drstewen** [comment]
@TheAlphamerc even so , thank you for your efort, i will try again
