### ISSUE TITLE
Bottom Navigation

### ISSUE THREAD

**Issue by harlanerskine** [TheAlphamerc/flutter_twitter_clone#169]
I'm reviewing this clone to learn to be a better FlutterDart programmer. I noticed this Twitter clone is not doing a behavior that Twitter does. 

When you navigate to a new page in the settings menu, the bottom navigation should persist like in the Twitter app, but I don't see that happening here.

The bottom navigation should be maintained within the settings screens to better evaluate Twitter's iOS app.

I'm trying to learn how to do this behavior. Does anyone have something they can point me to that works? Many thanks.

**Comment by TheAlphamerc** [comment]
Hi @harlanerskine, The Fwitter's bottom navigation bar is designed to replicate Twitter's android app behaviour and I am pretty sure it is working like that. I have't check Twitter's iOS app so I can't say about it.
