### ISSUE TITLE
is there any chance that we can have a look at the firestore schema (structure)  

### ISSUE THREAD

**Issue by amoo12** [TheAlphamerc/flutter_twitter_clone#171]
Hi, amazing work here mate

1. is there any chance that we can check the firestore schema (structure), I would like to have a look at the way you structure firestore collections.

2. are you using cloud functions to propagate any data changes? 

I am trying to find solutions for some scenarios for example: 
where we need to update older tweets when the user changes their profile picture. I believe that this is still an active issue with Fwitter.

you might want to check this out, this project provides solid solutions to such scenarios. 

https://medium.com/@garyalexanderpiong/building-a-working-instagram-clone-using-flutter-and-firebase-1c9f9bb960ef

**Comment by TheAlphamerc** [comment]
@amoo12 Sharing `firestore` database screenshots for your reference



## Main Collections
<img width="1256" alt="Screenshot 2021-05-16 at 1 35 06 PM" src="https://user-images.githubusercontent.com/37103237/118390860-3cacdf80-b5e6-11eb-91b6-c484da599555.png">

## Message Collection 
<img width="1264" alt="Screenshot 2021-05-16 at 1 35 18 PM" src="https://user-images.githubusercontent.com/37103237/118390912-767de600-b5e6-11eb-89d5-9516d3bb2fc0.png">


## Profile Collection
<img width="632" alt="Screenshot 2021-05-16 at 1 35 47 PM" src="https://user-images.githubusercontent.com/37103237/118390920-7c73c700-b5e6-11eb-8e1f-7e4abcc5cf5e.png">

## Chat Users Inside Profile Collection
<img width="1266" alt="Screenshot 2021-05-16 at 1 36 30 PM" src="https://user-images.githubusercontent.com/37103237/118390933-931a1e00-b5e6-11eb-886f-e0d1e6cb3a0c.png">

## Following User inside Profile collection
<img width="1251" alt="Screenshot 2021-05-16 at 1 36 41 PM" src="https://user-images.githubusercontent.com/37103237/118390944-a62cee00-b5e6-11eb-87c4-036b49e32f7f.png">


## Notifications Inside Profile Collection
<img width="1248" alt="Screenshot 2021-05-16 at 1 36 58 PM" src="https://user-images.githubusercontent.com/37103237/118390950-ab8a3880-b5e6-11eb-915e-e450d94014bc.png">

##  Tweet Collection
<img width="1258" alt="Screenshot 2021-05-16 at 1 37 11 PM" src="https://user-images.githubusercontent.com/37103237/118390952-acbb6580-b5e6-11eb-8899-f3699f406e47.png">


If you also want to have a look into `realtime` database scheme then have a look here https://github.com/TheAlphamerc/flutter_twitter_clone/issues/21#issuecomment-652805530

**Comment by amoo12** [comment]
thank you @TheAlphamerc this will help a lot, I will go ahead and close this issue.

**Comment by ScottLee97** [comment]
Hi @TheAlphamerc, thank you so much for sharing this! 

Do you mind sharing with me the reason for having both timestamp and createdAt in your message documents? Wouldn't one be enough? 

Thanks in advance!

**Comment by TheAlphamerc** [comment]
Actually I added `timestamp` to replace `createdAt` parameter but didn't got time to implement it.

**Comment by vineetk1984** [comment]
Hi @TheAlphamerc , Thank you for sharing the schema of FireStore collection. I have created exactly the same schema on the Firebase. But it is still not saving the data in the firebase collection from app. However, the realtime database is working fine.  Is there anything needs to be configured in the app to send data to the firebase firestore collections. Kindly share.
