### ISSUE TITLE
automatic random end of username?

### ISSUE THREAD

**Issue by gulmensedat** [TheAlphamerc/flutter_twitter_clone#18]
automatic random end of username? How can I fix this situation?

**Comment by TheAlphamerc** [comment]
The random end is necessary at signup process to avoid duplicacy in username. If you still don't want random end then ask user to enter a suitable username and you have to make sure that the same username does not exist in the database.

**Comment by gulmensedat** [comment]
> The random end is necessary at signup process to avoid duplicacy in username. If you still don't want random end then ask user to enter a suitable username and you have to make sure that the same username does not exist in the database.

I have not yet found where to remove it?

**Comment by TheAlphamerc** [comment]
When a user creates a new account by doing email signup or signup through g-mail,  a new user is created at firebase and then his username is created using his name and firebase user id. You can find this code at lib > state > authState.dart
<img width="1209" alt="Screenshot 2020-04-21 at 9 28 17 AM" src="https://user-images.githubusercontent.com/37103237/79824184-3c2a2100-83b3-11ea-8f13-9ee9f138f967.png">

**Comment by gulmensedat** [comment]
> When a user creates a new account by doing email signup or signup through g-mail, a new user is created at firebase and then his username is created using his name and firebase user id. You can find this code at lib > state > authState.dart
> <img alt="Screenshot 2020-04-21 at 9 28 17 AM" width="1209" src="https://user-images.githubusercontent.com/37103237/79824184-3c2a2100-83b3-11ea-8f13-9ee9f138f967.png">

No, this is. helper > utility.dart 

String getUserName({String name, String id}) {
  String userName = '';
  name = name.split(' ')[0];
  id = id.substring(0, 4).toLowerCase();
  userName = '@$name$id';
  return userName;
}

  userName = '@$name$id';

**Comment by TheAlphamerc** [comment]
Yes `getUserName({String name, String id})` method is in utility class but it is called from `AuthState` class to create username.

**Comment by emiravdovic** [comment]
> Yes `getUserName({String name, String id})` method is in utility class but it is called from `AuthState` class to create username.

I create text input in signup page with name "userName"
how can I connect this userName impute with this  code here?

String getUserName({String name, String id}) {
String userName = '';
name = name.split(' ')[0];
id = id.substring(0, 4).toLowerCase();
userName = '@$name$id';
return userName;
}

**Comment by TheAlphamerc** [comment]
@emiravdovic when you click on the submit button call this method by passing username text and some id to it and it will return a combination of username and id.

``` dart
String username = "Emiravdovic";
String id = "abcd1234;
final usernameForDb = Utility.getUsername(name:username, id:id);
print(username);
```
