### ISSUE TITLE
How I will pass the uppdate page in  Release mode ?

### ISSUE THREAD

**Issue by aliaktas-tr** [TheAlphamerc/flutter_twitter_clone#187]
for play store i build in release mode and when I instal apk to my phone just open the update page and cant pass it.

**Comment by TheAlphamerc** [comment]
To bypass the update screen , In splash screen code remove the app version check condition

**Comment by aliaktas-tr** [comment]
I already tried. Sorry maybe I couldn't explain the problem. Normally aplication is work. But in release mode or release apk just open the update screen.

**Comment by TheAlphamerc** [comment]
This is because I have restricted the update screen to display in development mode. 
To avoid this you need to made below changes in Splash screen code.

#### Replace this
```dart
 void timer() async {
    final isAppUpdated = await _checkAppVersion();
    if (isAppUpdated) {
      cprint("App is updated");
      Future.delayed(Duration(seconds: 1)).then((_) {
        var state = Provider.of<AuthState>(context, listen: false);
        // state.authStatus = AuthStatus.NOT_DETERMINED;
        state.getCurrentUser();
      });
    }
  }
```

#### With
```dart
 void timer() async {
      Future.delayed(Duration(seconds: 1)).then((_) {
        var state = Provider.of<AuthState>(context, listen: false);
        // state.authStatus = AuthStatus.NOT_DETERMINED;
        state.getCurrentUser();
      });
  }
```

**Comment by aliaktas-tr** [comment]
Thank you bro,worked for me.
