### ISSUE TITLE
Display inapp notification on user follow event for Firestore DB Version

### ISSUE THREAD

**Issue by qwerty684** [TheAlphamerc/flutter_twitter_clone#189]
How to update to this work to the "firestore" version of the app..

**Comment by TheAlphamerc** [comment]
Hello @qwerty684, Can you explain your problem statement in detail ?

**Comment by qwerty684** [comment]
@TheAlphamerc  Problem is when I come to this part "[Intitilise firebase notification kDatabase]", is not same like in real time database..
![Screenshot 2021-07-09 at 14 27 32](https://user-images.githubusercontent.com/53181006/125078122-41f84900-e0c2-11eb-8922-21204e67f15e.png)

**Comment by TheAlphamerc** [comment]
Yes, it's because the firestore branch is not updated since a long time. Currently I am working on updating the project architecture on realtime branch. Once it is completed I'll update the same in firestore branch.
