### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by ajatsoft** [TheAlphamerc/flutter_twitter_clone#19]
I can get notifications...

my config:

**in app:**

<img width="501" alt="Captura de pantalla 2020-04-20 a las 12 23 58" src="https://user-images.githubusercontent.com/26198923/79742149-b0f15280-8302-11ea-9d41-920691409355.png">

**remote config:**

<img width="531" alt="Captura de pantalla 2020-04-20 a las 12 24 10" src="https://user-images.githubusercontent.com/26198923/79742190-bf3f6e80-8302-11ea-9be7-eda2a4a86452.png">

**remote config json:**

<img width="242" alt="Captura de pantalla 2020-04-20 a las 12 24 20" src="https://user-images.githubusercontent.com/26198923/79742241-cd8d8a80-8302-11ea-8a68-163438285046.png">

if I send notification since firebase is ok, but when I send a chat message not send notification.

thank you¡¡¡

**Comment by TheAlphamerc** [comment]
You are getting json data from remote getting so you have to extract value of `key` from data.

``` dart 
void getFCMServerKey() async {
    final RemoteConfig remoteConfig = await RemoteConfig.instance;
    await remoteConfig.fetch(expiration: const Duration(hours: 5));
    await remoteConfig.activateFetched();
    var data = remoteConfig.getString('FcmServerKey');
    if (data != null) {
      serverToken = jsonDecode(data)["key"];
    }
  } 
```

**Comment by ajatsoft** [comment]
yes, I configure it like my photos and I can't recibe notifications, I have to do anything else? 
thank you a lot

**Comment by TheAlphamerc** [comment]
First of all please check notification by sending from the Postman.
You can use below demo json for notification.
``` json
{
  "notification": {
    "body": "this is a body",
    "title": "this is a title"
  },
  "priority": "high",
  "data": {
    "click_action": "FLUTTER_NOTIFICATION_CLICK",
    "id": "1",
    "status": "done",
    "title":"title",
    "body":"body",
    "tweetId":"wert"
    
     
  },
  "to": "ADD DEVICE FCM TOKEN HERE"
}
```
#### Postman notification configuration
<img width="1378" alt="Screenshot 2020-04-23 at 10 40 44 PM" src="https://user-images.githubusercontent.com/37103237/80129134-48c99780-85b4-11ea-838f-7bb2290584c2.png">

<img width="1366" alt="Screenshot 2020-04-23 at 10 33 12 PM" src="https://user-images.githubusercontent.com/37103237/80129120-4404e380-85b4-11ea-971d-f4eeb76c9e66.png">

**Comment by ajatsoft** [comment]
{
    "multicast_id": 4493036613982111398,
    "success": 0,
    "failure": 1,
    "canonical_ids": 0,
    "results": [
        {
            "error": "MismatchSenderId"
        }
    ]
}

**Comment by TheAlphamerc** [comment]
Probably you are using incorrect server key. Check your server key first.

**Comment by ajatsoft** [comment]
i cheked it , and y try after generate another one, config in my photos is ok?

**Comment by TheAlphamerc** [comment]
Your config seems ok in the photo.  Please check you are using the correct FCM server key.

**Comment by ajatsoft** [comment]
Yes i use my server key, only have 1!!

Enviado desde mi iPhone

**Comment by TheAlphamerc** [comment]
I  haven't any idea what's wrong in your configuration. If your notification is not working with postman then it is obvious you have either missing something or not using correct values.
