### ISSUE TITLE
To remove this warning message you have to use [ScaffoldMessenger](https://api.flutter.dev/flutter/material/ScaffoldMessenger-class.html) to display snackbar.

### ISSUE THREAD

**Issue by shuaibidshuaib** [TheAlphamerc/flutter_twitter_clone#192]
To remove this warning message you have to use [ScaffoldMessenger](https://api.flutter.dev/flutter/material/ScaffoldMessenger-class.html) to display snackbar.

_Originally posted by @TheAlphamerc in https://github.com/TheAlphamerc/flutter_twitter_clone/issues/190#issuecomment-877139920_

pls im so new to  flutter framework and i have even try to read documentation about the "Snackbar" , but i still dont understand, can you pls produce the code for me, pls.

**Comment by TheAlphamerc** [comment]
Duplicate of https://github.com/TheAlphamerc/flutter_twitter_clone/issues/190
