### ISSUE TITLE
Google signIn doesnt proceed

### ISSUE THREAD

**Issue by shuaibidshuaib** [TheAlphamerc/flutter_twitter_clone#193]
Pls help me, i have configured enable google, auth services, but if i open the app, it stays on signin page , even if i click the google sign in button,it display email account,then if i click , it take me to no page,then disappers , pls help me
![screenshot_2](https://user-images.githubusercontent.com/87182339/125146901-b976aa00-e0bb-11eb-8619-17ed2a8e6e0a.jpg)

**Comment by TheAlphamerc** [comment]
It looks like you have missed some steps from Wiki while configuring the google login. Please revisit wiki section and make sure you followed the all steps specially below steps. Make sure you have created the  firebase project with `com.thealphamerc.flutter_twitter_clone_dev` package id.

<img width="909" alt="Screenshot 2021-07-10 at 8 53 22 AM" src="https://user-images.githubusercontent.com/37103237/125150286-50933e80-e15c-11eb-9c12-58522aa97837.png">

**Comment by shuaibidshuaib** [comment]
I have tried but still it doesnt, anyways i have enabled both firestore storage and real time database in my project, does that causes the problem, pls bros help me.

**Comment by shuaibidshuaib** [comment]
im kind of newbie to flutter

**Comment by TheAlphamerc** [comment]
@shuaibidshuaib Look at the below article to know more about google login.
https://medium.com/flutterdevs/google-sign-in-with-flutter-8960580dec96

**Comment by shuaibidshuaib** [comment]
ok thank you very much, you're really friendly & simple
