### ISSUE TITLE
Cannot run main.dart due to unsound null safety

### ISSUE THREAD

**Issue by nniiggeell** [TheAlphamerc/flutter_twitter_clone#194]
**Describe the bug**
When running, i get this error
![image](https://user-images.githubusercontent.com/77267877/125288678-fe673e80-e350-11eb-9722-f0a2e4512e09.png)

Is this a known issue? How can i fix it?

**Comment by TheAlphamerc** [comment]
Are you trying to run this for web ?

**Comment by loaishawar** [comment]
No from android. Phone

**Comment by TheAlphamerc** [comment]
Which version of flutter you are using?

**Comment by nniiggeell** [comment]
I am using 2.0.5

**Comment by TheAlphamerc** [comment]
Try run `flutter clean` and then `flutter pub get`
