### ISSUE TITLE
Splash screen hangs and doesnt proceed to next page

### ISSUE THREAD

**Issue by shuaibidshuaib** [TheAlphamerc/flutter_twitter_clone#195]
pls brother help me, i have been encountering this problem , and besides i have set everything right, the splash screen snack bar goes on continously without taking me to next page , pls heres the video](https://drive.google.com/file/d/1QtJw773VYNuYcOCvQvls2kvaeW-hBl_F/view?usp=sharing)

**Comment by TheAlphamerc** [comment]
@shuaibidshuaib  can you share console log ?

**Comment by shuaibidshuaib** [comment]
this is the only error in console; 
{
	"resource": "/C:/Users/MTGSTCKN/Documents/flutter_twitter_clone/lib/helper/routes.dart",
	"owner": "dart",
	"code": {
		"value": "unused_import",
		"target": {
			"$mid": 1,
			"external": "https://dart.dev/tools/diagnostic-messages#unused_import",
			"path": "/tools/diagnostic-messages",
			"scheme": "https",
			"authority": "dart.dev",
			"fragment": "unused_import"
		}
	},
	"severity": 2,
	"message": "Unused import: '../ui/page/profile/EditProfilePage.dart'.\nTry removing the import directive.",
	"source": "dart",
	"startLineNumber": 33,
	"startColumn": 8,
	"endLineNumber": 33,
	"endColumn": 49,
	"tags": [
		1
	]
}

**Comment by shuaibidshuaib** [comment]
and in my console firebase,(dashboard) it show that it has been used, like this it has been used . also i have enabled both firebase database and realtime database,but i didnt enabled  "STORAGE", pls does that triggers the problem?, also i'm using flutter sdk version 2.0.6 , is it the problem,pls help me out

>

**Comment by TheAlphamerc** [comment]
@shuaibidshuaib in order to run project without any issue you have to follow every steps written in. [Wiki](https://github.com/TheAlphamerc/flutter_twitter_clone/wiki/Gettings-Started)

**Comment by shuaibidshuaib** [comment]
Thank you , very much brother, everything now works expect , when i try to create account using the sign up with google button , it does shows me the accounts (google) present in the phone, but when i click it doesn't create account an account, and i have enabled google in the Firebase authentication part, pls brother whats your view on this, i need to submit this project tomorrow morning, and also nothing is present on the logs console

**Comment by TheAlphamerc** [comment]
Have you added SHA-1 fingerprint to firebase ? If yes then I suggest you to follow the below steps.

* Go to Firebase project.
* Select Authentication from the sidebar.
* Delete all Google user's accounts.
* Delete firebase realtime database.
* Run the project and try to create user account using Google id.

**Comment by shuaibidshuaib** [comment]
ok bros, thank you, i will try to do that, .

**Comment by shuaibidshuaib** [comment]
Thank you brother, everything, works and now i need only one thing, i will be submitting my project in 5 hrs.Pls brother how can i change this "Fwitter for android" to "Wings for android" pls help brother
![Screenshot_2021-07-19-02-29-24-247_com thealphamerc flutter_twitter_clone_dev](https://user-images.githubusercontent.com/87182339/126090677-4878a5e0-7db6-4a70-9e30-bc503c708367.jpg)

**Comment by TheAlphamerc** [comment]
@shuaibidshuaib this line can be changed at https://github.com/TheAlphamerc/flutter_twitter_clone/blob/e138c997cba5731e154a36a26f89c9360fd56e3c/lib/widgets/tweet/widgets/tweetIconsRow.dart#L139

**Comment by shuaibidshuaib** [comment]
Thank you
