### ISSUE TITLE
Blue tick verification.

### ISSUE THREAD

**Issue by shuaibidshuaib** [TheAlphamerc/flutter_twitter_clone#200]
Hello there brother , i have just submit my project to my professor yesterday regarding to knowledge i got from your, twitter clone my professor was very impressed, thank you very much sir alphamerc, now im finished, But brother pls i there anyway i can apply a blue tick to users manually from Firebase console. like is there anyway to turn this into false from the database manually, thats in firebase console.
![Capture](https://user-images.githubusercontent.com/87182339/126404536-2c2aeb87-4068-42c0-8c65-0993b32a2ef9.JPG)

**Comment by TheAlphamerc** [comment]
Yes, It can be changed from firebase database but it will be changed automatically when user login into the app. To avoid this you need to remove `reloadUser()` method from `getProfileUser()` method in `AuthState`

https://github.com/TheAlphamerc/flutter_twitter_clone/blob/e138c997cba5731e154a36a26f89c9360fd56e3c/lib/state/authState.dart#L372

**Comment by shuaibidshuaib** [comment]
It works now but brother , have you noticed a bug, that if you click "follow" button when you find a user in followings of others or followers, the button doesnt changes to following, pls help me to fix that, people that are using my project now are complaining.

**Comment by TheAlphamerc** [comment]
Yeah, I know that. It is a feature which is not been implemented yet.
