### ISSUE TITLE
Video post .

### ISSUE THREAD

**Issue by shuaibidshuaib** [TheAlphamerc/flutter_twitter_clone#202]
Pls sir is there anyway, that i can post video to the profile page, instead of only pics, if possible pls sir provide me the code. also the code to be able to play video if posted, i'm curious to implement this feature .

**Comment by TheAlphamerc** [comment]
The solution of the problem is pretty simple. The way we are saving the image to firebase storage and getting its URL, the same way we can save a video to firebase storage and save its URL in post model.

**Comment by shuaibidshuaib** [comment]
ok thanks

**Comment by shuaibidshuaib** [comment]
But this triggers my last  question sir, how can i implement the code that will show the trending hashtags, similar to that of twitter , i really need that feature sir
