### ISSUE TITLE
flutter_link_preview ^1.5.6 requires http ^0.12.2 but http ^0.13.3 is configured

### ISSUE THREAD

**Issue by giohappy** [TheAlphamerc/flutter_twitter_clone#205]
**Describe the bug**
`pub get` throws an error since flutter_link_preview ^1.5.6 requires http ^0.12.2 but http ^0.13.3 is configured (commit https://github.com/TheAlphamerc/flutter_twitter_clone/commit/b1d9f333f5d4882b82090d6c31480159e9475612)

**To Reproduce**
1. Clone the repo
2. Run `flutter pub get`
3. Error is thrown

```
Because flutter_twitter_clone depends on flutter_link_preview ^1.5.6 which depends on http ^0.12.1, http ^0.12.1 is required.
So, because flutter_twitter_clone depends on http ^0.13.3, version solving failed.
Running "flutter pub get" in flutter_twitter_clone...                   
pub get failed (1; So, because flutter_twitter_clone depends on http ^0.13.3, version solving failed.)
```

**App**
- master branch

**Other infos**
 - Windows 10
 - Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
 - Framework • revision f4abaa0735 (7 weeks ago) • 2021-07-01 12:46:11 -0700
 - Engine • revision 241c87ad80
 - Tools • Dart 2.13.4

**Comment by TheAlphamerc** [comment]
To fix this issue you have to upgrade `flutter_link_preview` package version to 0.13.3. Sice author hasn't upgraded this in package so you have to do it manually.  

* Go to .pub-cache folder for flutter sdk.
* Find flutter_link_preview-1.5.6 folder and open pubspec.yaml file.
* Update http version from ^1.5.6 to ^1.13.3
Check below screenshot.

<img width="967" alt="Screenshot 2021-09-11 at 10 43 51 AM" src="https://user-images.githubusercontent.com/37103237/132937210-573e00d0-4295-4b40-9803-e15cb5136473.png">

**Comment by MaizerGomes** [comment]
Not really a good practice, but I managed to overcome the same situation by overriding the http dependency.

Add inside the pubspec.yaml file the following
  `dependency_overrides:
  http: ^0.13.3`

**Comment by iamaryanshandilya** [comment]
Because google_fonts 2.1.0 depends on http ^0.13.0 and no versions of google_fonts match >2.1.0 <3.0.0, google_fonts ^2.1.0 requires http ^0.13.0.
So, because flutter_twitter_clone depends on both http ^0.12.2 and google_fonts ^2.1.0, version solving failed.

**Comment by iamaryanshandilya** [comment]
> Not really a good practice, but I managed to overcome the same situation by overriding the http dependency.
> 
> Add inside the pubspec.yaml file the following
> `dependency_overrides: http: ^0.13.3`

Please tell me, how to override a dependency, I am new to flutter so I don't know how to do that.

**Comment by MaizerGomes** [comment]
Just copy the 

> > Not really a good practice, but I managed to overcome the same situation by overriding the http dependency.
> > Add inside the pubspec.yaml file the following
> > `dependency_overrides: http: ^0.13.3`
> 
> @MaizerGomes, @TheAlphamerc Please tell me, how to override a dependency, I am new to flutter so I don't know how to do that.

Open the `pubspec.yaml` file, add a line above the line `dev_dependencies:` and write the following lines:
`dependency_overrides:`
`    http: ^0.13.3`

Pay attention to the indentation.
First line with no indentation and the second one with one level indentation (one tab).

Then run `flutter pub get`

And finally `flutter run`

I'm new to flutter as well.
I'm not sure if this is the best way or not, but I can tell that flutter doesn't like it since it throws some warnings when running pub get. But for testing purposes I believe it's all right.

**Comment by TheAlphamerc** [comment]
> Not really a good practice, but I managed to overcome the same situation by overriding the http dependency.
> 
> Add inside the pubspec.yaml file the following
> `dependency_overrides: http: ^0.13.3`

Agreed, it's totally a good practice to override dependency if any conflicts occured.

**Comment by HoracioLopezCarvajal** [comment]
I have not been able to solve the error with what is proposed in this post. I have not been able to solve the error with what is proposed in this post, it keeps giving me the same error

**Comment by TheAlphamerc** [comment]
> Not really a good practice, but I managed to overcome the same situation by overriding the http dependency.
> 
> Add inside the pubspec.yaml file the following 
```dart
dependency_overrides:
 http: ^0.13.3
```

@HoracioLopezCarvajal did you added this line in pubspec.yml file ?
