### ISSUE TITLE
app clash debug on iphone 11 

### ISSUE THREAD

**Issue by keenjoe007** [TheAlphamerc/flutter_twitter_clone#207]
**Describe the bug**
App crashes after launch when trying to debug on iphone 11

**To Reproduce**

1.Debug from vscode at lib/main.dart.
2.Installed app to iphone.
3.app open
4.clash

**Expected behavior**
show splash screen

**Screenshots**
<img width="1135" alt="スクリーンショット 2021-09-08 16 43 09" src="https://user-images.githubusercontent.com/4803736/132467614-9846bb7c-4bb6-4c0c-a421-9be0c3bc97e4.png">

**Smartphone (please complete the following information):**
 - Device: iphone11
 - OS: ios
 - Version: 14.7.1 

**Additional context**

**Comment by TheAlphamerc** [comment]
I haven't check this on the iOS platform for a long time so can't say about this error.
