### ISSUE TITLE
Push notification opening the feedpost detail page

### ISSUE THREAD

**Issue by karambitmonger** [TheAlphamerc/flutter_twitter_clone#208]
Hi @TheAlphamerc ,i have been able to tweak and customise the code to send push notification when a user comments on a twwet. It is working well and redirecting me to the feedpost detail page of the tweet. Problem is when i click the push notification,the fedpost detail opens but is blank/empty. The postId i am using to navigate to the tweet detail page is the original tweet key of the tweet.
![Screenshot from 2021-09-16 12-21-25](https://user-images.githubusercontent.com/70143156/133586990-692249cc-1188-4872-b7d1-c6c296ff1624.jpeg)
I think the problem is with the key/postId i am passing through the navigator to feedPostDetailPage,how do i go about this?

**Comment by TheAlphamerc** [comment]
@karambitmonger are doing good but forget one small step before navigating to feedPostDetailPage.
If you check the code where the user is redirected to post detail, You will find there is a code to get post detail using its id. So basically add the below code just redirecting to post detail (Line - 70).

```dart
      var feedstate = Provider.of<FeedState>(context, listen: false);
      feedstate.getpostDetailFromDatabase(id);
 ```

**Comment by karambitmonger** [comment]
@TheAlphamerc thanks,it now works beautifully
