### ISSUE TITLE
Firestore DB

### ISSUE THREAD

**Issue by qwerty684** [TheAlphamerc/flutter_twitter_clone#209]
When This Features will be update on Firestore Branch.. Thank you! 👍  @TheAlphamerc

**Comment by TheAlphamerc** [comment]
@qwerty684 which features you are talking about?

**Comment by qwerty684** [comment]
@TheAlphamerc  For example this last update with Bookmark posts, and all other updates where changes are related to database

**Comment by TheAlphamerc** [comment]
I didn't have any timeline for that but I'll implement these changes in firstore branch very soon.
