### ISSUE TITLE
Follow button bug

### ISSUE THREAD

**Issue by gulmensedat** [TheAlphamerc/flutter_twitter_clone#21]
I created a new user. I went to the search screen. I clicked on the user I created before. I said follow and detected a mistake there. When I first clicked the follow button, I seemed to switch to that profile. Then when I click on profile it improved.

**Comment by TheAlphamerc** [comment]
@gulmensedat I have tested the app but didn't able to produce the error. Please let me know the detailed steps to reproduce this error.

**Comment by gulmensedat** [comment]
> @gulmensedat I have tested the app but didn't able to produce the error. Please let me know the detailed steps to reproduce this error.

This error doesn't happen every time we click the follow button. I guess try to follow more than 1 user in a row, when you press the follow button for the first time, it is not active in the first time and there is an account transition. I shot a video for the error scenario.

https://vimeo.com/410279633

**Comment by iamkaps1** [comment]
Can we have ios versiona as well?
and where is the db schema please

**Comment by TheAlphamerc** [comment]
### All tables
<img width="334" alt="Screenshot 2020-07-02 at 11 27 29 AM" src="https://user-images.githubusercontent.com/37103237/86322474-b0592e80-bc58-11ea-823b-8d32e5101746.png">

### Chat table
<img width="650" alt="Screenshot 2020-07-02 at 11 27 22 AM" src="https://user-images.githubusercontent.com/37103237/86322495-b94a0000-bc58-11ea-80f7-22b760097e26.png">

### Chat user table
<img width="745" alt="Screenshot 2020-07-02 at 11 27 50 AM" src="https://user-images.githubusercontent.com/37103237/86322507-bf3fe100-bc58-11ea-9542-e11b7339c489.png">

### Notification table
<img width="604" alt="Screenshot 2020-07-02 at 11 28 11 AM" src="https://user-images.githubusercontent.com/37103237/86322513-c2d36800-bc58-11ea-9cc1-b1e50bd2a360.png">

### Profile table
<img width="743" alt="Screenshot 2020-07-02 at 11 29 19 AM" src="https://user-images.githubusercontent.com/37103237/86322524-c666ef00-bc58-11ea-874c-7dd4577d39fa.png">

### Tweet table
<img width="716" alt="Screenshot 2020-07-02 at 11 31 30 AM" src="https://user-images.githubusercontent.com/37103237/86322528-c961df80-bc58-11ea-9433-cdceed8deb44.png">

**Comment by iamkaps1** [comment]
Thank you Sir
Kapil Gaur
gaur.kapil@yahoo.co.in
+91 997 100 2669
