### ISSUE TITLE
Problem building application , cloud store problem

### ISSUE THREAD

**Issue by shuaibidshuaib** [TheAlphamerc/flutter_twitter_clone#210]
Please guys help me , I'm stuck in the following error.

FAILURE: Build failed with an exception.                               

    What went wrong: A problem occurred configuring project ':cloud_firestore'.

    Failed to create Jar file C:\Users\MTGSTCKN.gradle\caches\jars-8\99abe0125edcf1bf21d3955d59f6b74c\gradle-3.5.4.jar. Failed to notify project evaluation listener. Could not get unknown property 'android' for project ':cloud_firestore' of type org.gradle.api.Project. Could not find method implementation() for arguments [project ':firebase_core'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

    Try: Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

    Get more help at https://help.gradle.org

BUILD FAILED in 16m 26s Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done 998.4sGradle task assembleRelease failed with exit code 1

**Comment by TheAlphamerc** [comment]
@shuaibidshuaib pls mention the branch you are using.

**Comment by shuaibidshuaib** [comment]
Sir this is the project, im trying to make a section in twitter clone, to make it a way others in the app could hire things, so i used some of its code[https://github.com/Singh-Shivani/hopOn](url)

**Comment by shuaibidshuaib** [comment]
But im getting the error mentioned

**Comment by shuaibidshuaib** [comment]
Is it because my firebase firestore  rules have expired , also im using flutter 2.0.5
