### ISSUE TITLE
FLUTTER WEB

### ISSUE THREAD

**Issue by Hosea987** [TheAlphamerc/flutter_twitter_clone#212]
HI @TheAlphamerc ,I think a web version for this app is long overdue. At least do a starting point for us to build on

**Comment by TheAlphamerc** [comment]
Hello @Hosea987, Yes I know this is pending from a long time but before this I have to add some new feature in main branch and have update firestone branch. Once this is done I'll think about web version.

**Comment by Hosea987** [comment]
@TheAlphamerc cool
