### ISSUE TITLE
Set up firebase deep links

### ISSUE THREAD

**Issue by Hosea987** [TheAlphamerc/flutter_twitter_clone#214]
hi @TheAlphamerc ,how do we setup firebase deep dynamic links on firebase console?

**Comment by TheAlphamerc** [comment]
Hello @Hosea987. Please have a look at this good article about setting up dynamic links using firebase -> https://betterprogramming.pub/deep-linking-in-flutter-with-firebase-dynamic-links-8a4b1981e1eb
