### ISSUE TITLE
Because flutter_link_preview 1.5.6 depends on http ^0.12.1 and no versions of flutter_link_preview match >1.5.6 <2.0.0, flutter_link_preview ^1.5.6 requires http ^0.12.1. So, because flutter_twitter_clone depends on both flutter_link_preview ^1.5.6 and http ^0.13.3, version solving failed.

### ISSUE THREAD

**Issue by HoracioLopezCarvajal** [TheAlphamerc/flutter_twitter_clone#216]
Because flutter_link_preview 1.5.6 depends on http ^0.12.1 and no versions of flutter_link_preview match >1.5.6 <2.0.0, flutter_link_preview ^1.5.6 requires http ^0.12.1.
So, because flutter_twitter_clone depends on both flutter_link_preview ^1.5.6 and http ^0.13.3, version solving failed.

**Comment by TheAlphamerc** [comment]
Hello @HoracioLopezCarvajal, You will find your answer here -> https://github.com/TheAlphamerc/flutter_twitter_clone/issues/205#issuecomment-921826943
