### ISSUE TITLE
I am trying to move the project to the web and pass all the functionalities that it has left to improve.  When I try to pass it to web, it loads but the screen remains blank, it does not give any error

### ISSUE THREAD

**Issue by HoracioLopezCarvajal** [TheAlphamerc/flutter_twitter_clone#219]
I am trying to move the project to the web and pass all the functionalities that it has left to improve.

When I try to pass it to web, it loads but the screen remains blank, it does not give any error

**Comment by Dore940** [comment]
Try to run it directly in the terminal 
flutter --run
and choose one of the browser available

**Comment by Hosea987** [comment]
@Dore940 have you been able to run the app on web? If yes,would you mind sharing the code
