### ISSUE TITLE
Feed page

### ISSUE THREAD

**Issue by qwerty684** [TheAlphamerc/flutter_twitter_clone#221]
Hello @TheAlphamerc, how can i hide from feed page coments which i like owner of profile make to some post.. I want to on feed page be visible just main post, if i create coment to this post or to some other user post to not display to me on feed page also, same like other user can't seen it till the not go to details page..
Thank you.

**Comment by TheAlphamerc** [comment]
Do you want to hide comments post from home page ?

**Comment by qwerty684** [comment]
@TheAlphamerc  Yes, i wanna hide comment posts..  But if i wanna create regular post only text then to be visible like how is now.. So basicly only comment post to be hided..

**Comment by TheAlphamerc** [comment]
@qwerty684 In feedstate file there is method named `getTweetLoist` you have remove a condition where we are allowing logged-in users' tweets to display on feed page. If you remove `x.user!.userId != userModel.userId` condition then you will see no comments on feed page.
<img width="1154" alt="Screenshot 2022-01-08 at 10 34 03 AM" src="https://user-images.githubusercontent.com/37103237/148632356-19dc6f2f-8051-42e6-af47-7659b1db22c6.png">
