### ISSUE TITLE
Well I've changed the app quite a bit from what it was. Contact me via discord CryptoMasterFr#5250 if you more information. @sayemmh

### ISSUE THREAD

**Issue by HoracioLopezCarvajal** [TheAlphamerc/flutter_twitter_clone#222]
Hi I'm trying to finish the twitter clone project to improve flutter.
How did you manage to put it on the web?
Greetings mate

**Comment by TheAlphamerc** [comment]
Hi, I haven't tried to run this project on web. I think @DovAzencot can help you with this. He is able to deploy and run this project on the web successfully.
