### ISSUE TITLE
Build apk problem

### ISSUE THREAD

**Issue by qwerty684** [TheAlphamerc/flutter_twitter_clone#231]
@TheAlphamerc Hello, hawe problem with build apk, code don't hawe any error and work fine on ios devices, but when i try to build apk or to run on android devices it show error down belove..

![Screenshot 2022-01-02 at 00 03 37](https://user-images.githubusercontent.com/53181006/147861881-2636a4f4-fb8f-41dc-b280-dcd41f2ba6f2.png)

**Comment by TheAlphamerc** [comment]
@qwerty684 do try to run below commands before building apk.
* `flutter clean`
* `flutter pub get`

**Comment by qwerty684** [comment]
@TheAlphamerc  I try but is same... Error is there..

**Comment by TheAlphamerc** [comment]
@qwerty684 Are you able to run app on android ? BTW I just created apk without facing any issue.

**Comment by qwerty684** [comment]
@TheAlphamerc  No it show same error every time i try to  run on real device or simulator, or  when we build apk..
