### ISSUE TITLE
remove sing up and google login button

### ISSUE THREAD

**Issue by mattis1231231** [TheAlphamerc/flutter_twitter_clone#232]
I would therefore like that when you come to the splash screen that you can only log in and the I would also like to remove the google login button who can help me with that thanks in advance

**Comment by Amhaz1** [comment]
wow how do you manage to open it successful it keep showing me error, please can share your facebook or whatsapp number to me so that we can chat about programming please or send it to me through Hadhir01@gmail.com please send me email or reply to me

**Comment by TheAlphamerc** [comment]
@mattis1231231 You can find thos code in selectAuthMethod file and search for the code you want to remove.
