### ISSUE TITLE
Search for the username instead of being automatic listed of all users on the search page. 

### ISSUE THREAD

**Issue by DisEasDaWay** [TheAlphamerc/flutter_twitter_clone#233]
Happy new year! I did try to follow your instruction on the search page

![image](https://user-images.githubusercontent.com/97230295/148380268-811be3c4-6604-4e18-af75-3417fbfc1582.png)

It's is working but it causes an error too. when I navigate to the search page then instantly go to the feed page. it throws an error automatically.

![image](https://user-images.githubusercontent.com/97230295/148380757-c8cd413e-209f-41e8-b360-46ed15d28d9e.png)

**Comment by Amhaz1** [comment]
wow how do you manage to open it successful please can share your facebook or whatsapp number to me so that we can chat about programming please or send it to me through hadhir01@gmail.com please send me email or reply to me

**Comment by TheAlphamerc** [comment]
@DisEasDaWay Can you take latest code pull and check  ?

**Comment by DisEasDaWay** [comment]
Hi, @TheAlphamerc I did pull the latest version but the app is not working because of this line. It causes the app to stop.
![image](https://user-images.githubusercontent.com/97230295/149254986-055dcd6b-771f-446f-abac-49f4adcf771a.png)

**Comment by DisEasDaWay** [comment]
Hi, I just set it to false then the app is working properly. and also the original error that I posted is not visible anymore the app is working properly now. 

But can you tell me more about the softwrap because it causes the app to stop working? 

Thank you!

**Comment by TheAlphamerc** [comment]
@DisEasDaWay `softWrap` is a boolean type property in `Text` widget and can be used when you want to break the line when found soft line break in text. Check its documentation here -> https://api.flutter.dev/flutter/widgets/Text/softWrap.html
