### ISSUE TITLE
Bug When Posting A Comment

### ISSUE THREAD

**Issue by mowet601** [TheAlphamerc/flutter_twitter_clone#237]
E/flutter (16695): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: type 'Null' is not a subtype of type 'String'
E/flutter (16695): #0      _ComposeTweetReplyPageState._submitButton (package:flutter_twitter_clone/ui/page/feed/composeTweet/composeTweet.dart:140:9)
E/flutter (16695): <asynchronous suspension>
E/flutter (16695):

**Comment by TheAlphamerc** [comment]
@mowet601 Do take pull from latest code and check again.

**Comment by TheAlphamerc** [comment]
@mowet601 let me know if you still facing this issue.
