### ISSUE TITLE
Notification Error

### ISSUE THREAD

**Issue by gulmensedat** [TheAlphamerc/flutter_twitter_clone#24]
════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
Tried to listen to a value exposed with provider, from outside of the widget tree.

This is likely caused by an event handler (like a button's onPressed) that called
Provider.of without passing `listen: false`.

To fix, write:
Provider.of<NotificationState>(context, listen: false);

It is unsupported because may pointlessly rebuild the widget associated to the
event handler, when the widget tree doesn't care about the value.

The context used was: HomePage(dependencies: [_DefaultInheritedProviderScope<AppState>], state: _HomePageState#074c3)
'package:provider/src/provider.dart':
Failed assertion: line 193 pos 7: 'context.owner.debugBuilding || listen == false || _debugIsInInheritedProviderUpdate'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      Provider.of (package:provider/src/provider.dart:193:7)
#3      _HomePageState._checkNotification.<anonymous closure> (package:twitterapp2/page/homePage.dart:86:28)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
#5      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1049:9)
#6      SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:850:7)
...

**Comment by TheAlphamerc** [comment]
Which version of flutter SDK you are using ?

**Comment by gulmensedat** [comment]
> Which version of flutter SDK you are using ?

v1.12.13+hotfix.9
v1.16.3
v1.16.2

**Comment by TheAlphamerc** [comment]
Do you have the latest code pull?

**Comment by gulmensedat** [comment]
I got this error after reinstalling it. I think the reason I got this error is because I did not set the notification correctly. I couldn't find how to produce Key.

**Comment by TheAlphamerc** [comment]
Please answer below queries first.
1. Do you have latest project code on your system?
2. Are you talking about FCM server key ?

**Comment by gulmensedat** [comment]
1. Has the most current version.
2. Yes.

**Comment by TheAlphamerc** [comment]
To get information about FCM key please check this [issue](https://github.com/TheAlphamerc/flutter_twitter_clone/issues/28#issue-611695533)

**Comment by gulmensedat** [comment]
> To get information about FCM key please check this [issue](https://github.com/TheAlphamerc/flutter_twitter_clone/issues/28#issue-611695533)

key okey.

**Comment by gulmensedat** [comment]
In the latest project codes, the member opens the register, but nothing in the database.

**Comment by TheAlphamerc** [comment]
I didn't get you. Can you explain it what are you trying to say?

**Comment by gulmensedat** [comment]
> I didn't get you. Can you explain it what are you trying to say?

I say create an account
Authentication occurs
Nothing happens in the database

**Comment by TheAlphamerc** [comment]
Please share error console logs

**Comment by gulmensedat** [comment]
> Please share error console logs

I solved the problem, I did not realize that there was a problem of rules.

**Comment by gulmensedat** [comment]
But I'm still getting this error.


```
════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
Tried to listen to a value exposed with provider, from outside of the widget tree.

This is likely caused by an event handler (like a button's onPressed) that called
Provider.of without passing `listen: false`.

To fix, write:
Provider.of<NotificationState>(context, listen: false);

It is unsupported because may pointlessly rebuild the widget associated to the
event handler, when the widget tree doesn't care about the value.

The context used was: HomePage(dependencies: [_DefaultInheritedProviderScope<AppState>], state: _HomePageState#db1af)
'package:provider/src/provider.dart':
Failed assertion: line 193 pos 7: 'context.owner.debugBuilding || listen == false || _debugIsInInheritedProviderUpdate'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      Provider.of (package:provider/src/provider.dart:193:7)
#3      _HomePageState._checkNotification.<anonymous closure> (package:twitterapp2/page/homePage.dart:86:28)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
#5      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1049:9)
#6      SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:850:7)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

```

**Comment by TheAlphamerc** [comment]
Add below provider version in pubspec.yml
`provider: ^3.2.0`

**Comment by TheAlphamerc** [comment]
@gulmensedat  is it works?

**Comment by gulmensedat** [comment]
> is it works?

yes thanks.
