### ISSUE TITLE
Show other comments on the reply.

### ISSUE THREAD

**Issue by DisEasDaWay** [TheAlphamerc/flutter_twitter_clone#240]
Hi I know it is not a feature of Ftwitter but can you guide me to properly show all the comments on the post in the reply?

I would like to look just like the feedpostdetails but have a reply or comment text area.

Thank you and much appreciated.

**Comment by TheAlphamerc** [comment]
@DisEasDaWay what do you mean by showing all comments on the post ? As from your statement my understanding is you want to display all nested replies in comments list of main tweet right?
