### ISSUE TITLE
Which version of Flutter SDK is being used?

### ISSUE THREAD

**Issue by AnoopMasterCoder** [TheAlphamerc/flutter_twitter_clone#241]

**Comment by AnoopMasterCoder** [comment]
Can someone please tell me which version of Flutter is being used because I am getting some build errors and exceptions.

**Comment by TheAlphamerc** [comment]
@AnoopMasterCoder I am using `Flutter 2.8.1 • channel stable` version. Can you share error screenshots here ?

**Comment by AnoopMasterCoder** [comment]
@TheAlphamerc  Thanks for your reply.

I was actually using Flutter 2.5.2 but now I have upgraded to latest version.

I am getting a few errors: 
![Error](https://user-images.githubusercontent.com/81739479/151659997-cc874412-8db4-443c-bc6e-b9ca1edea97d.png)

**Comment by TheAlphamerc** [comment]
@AnoopMasterCoder The error has nothing to do with Flutter version. You are getting this error because inside `create TweetModel()` method there is some code which is trying to access null value.

**Comment by AnoopMasterCoder** [comment]
Thanks but I am getting many exceptions like these.

How can I get rid of these errors ?

**Comment by TheAlphamerc** [comment]
@AnoopMasterCoder Can you answer the below-mentioned question?

1. Did you have the latest code on your system?
2. Have to configured firebase in the project?
3. Do share console logs of all errors you are getting.

**Comment by AnoopMasterCoder** [comment]
1. Yes I have the latest code on my system.
2. Yes I have configured my project in Firebase.
3. I will share my logs when I run the project as I am currently busy.
