### ISSUE TITLE
 login problem

### ISSUE THREAD

**Issue by TeaqariaWTF** [TheAlphamerc/flutter_twitter_clone#252]
Android 12

I can't log in even though my password is correct
![Screenshot_20220227-224510_Fwitter](https://user-images.githubusercontent.com/90970076/155897378-81ec16c2-1770-4713-8a92-068be8027dd1.png)

**Comment by TeaqariaWTF** [comment]
my e-mail address is correct

**Comment by TheAlphamerc** [comment]
@TeaqariaWTF  How did you create your account?

**Comment by TeaqariaWTF** [comment]
> @TeaqariaWTF How did you create your account?

Do I need to create a new account?

**Comment by TheAlphamerc** [comment]
@TeaqariaWTF If you are trying to login into Fwitter app then you'll need a Fwitter account.
