### ISSUE TITLE
iOS appbar white space 

### ISSUE THREAD

**Issue by DisEasDaWay** [TheAlphamerc/flutter_twitter_clone#256]
Hey, bro, the iOS appbar have white space? how to fix this ?
![image](https://user-images.githubusercontent.com/97230295/158484201-07548555-ecdf-44dd-ba32-4b4b10603260.png)

**Comment by TheAlphamerc** [comment]
@DisEasDaWay Can you share full-screen screenshot ?

**Comment by DisEasDaWay** [comment]
![image](https://user-images.githubusercontent.com/97230295/158692823-e8ece701-4b4e-4656-bb3b-57716c8bd4f7.png)
