### ISSUE TITLE
Messages are not sent

### ISSUE THREAD

**Issue by CoderXXXXX** [TheAlphamerc/flutter_twitter_clone#258]
In the release version app - after the first installation of the application, it is not possible to send someone the first private message. After clicking the submit button, nothing happens. However, if the application is restarted, then the messages are already being sent. How can I catch this error? (everything is fine in the emulator, but on a physical device after install, it's a disaster).

**Comment by CoderXXXXX** [comment]
I was able to get this information.
Error is: _CastError (Null check operator used on a null value)
in Line "senderName: authstate.user!.displayName!);"

**Comment by TheAlphamerc** [comment]
@CoderXXXXX I am not able to reproduce this issue.
