### ISSUE TITLE
Dynamic Link help

### ISSUE THREAD

**Issue by rhtzy** [TheAlphamerc/flutter_twitter_clone#259]
**How to activate dynamic link ?**

**Comment by rhtzy** [comment]
Note: C:\Users\Admin\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_analytics-9.0.3\android\src\main\java\io\flutter\plugins\firebase\analytics\FlutterFirebaseAnalyticsPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\Users\Admin\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_dynamic_links-4.0.2\android\src\main\java\io\flutter\plugins\firebase\dynamiclinks\FlutterFirebaseDynamicLinksPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\Admin\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_dynamic_links-4.0.2\android\src\main\java\io\flutter\plugins\firebase\dynamiclinks\FlutterFirebaseDynamicLinksPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\Users\Admin\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in-5.2.1\android\src\main\java\io\flutter\plugins\googlesignin\GoogleSignInPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by TheAlphamerc** [comment]
@rhtzy You can find a detailed documentation about dynamic link here -> https://firebase.flutter.dev/docs/dynamic-links/create.
