### ISSUE TITLE
Message und Notification

### ISSUE THREAD

**Issue by emiravdovic** [TheAlphamerc/flutter_twitter_clone#26]
How to make that last notification und last message be always on the top of list..
Und wil be inplement that we can share videos on the feed page und on the messages chat..
Very Good Project!! 👍

**Comment by TheAlphamerc** [comment]
The last notification on top is not implemented yet, but surely will be considered in a future release.

**Comment by TheAlphamerc** [comment]
> The last notification on top is not implemented yet, but surely will be considered in a future release.

Feature implemented, other remaining feature will be resolved soon.
