### ISSUE TITLE
if a user comment on a tweet it displays as a new tweet. how can i stop this ?

### ISSUE THREAD

**Issue by otukpere** [TheAlphamerc/flutter_twitter_clone#261]
if a user comment on a tweet it displays as a new tweet. how can i stop this ?

**Comment by TheAlphamerc** [comment]
On your home timeline you won't see comments of other users.

**Comment by TheAlphamerc** [comment]
There is another issue same as this. Check it here -> https://github.com/TheAlphamerc/flutter_twitter_clone/issues/221
