### ISSUE TITLE
login issue

### ISSUE THREAD

**Issue by HikaruIchijyo** [TheAlphamerc/flutter_twitter_clone#263]
**Describe the bug**
this error appears no matter which account i try to ligin 
![IMG_20220817_113044](https://user-images.githubusercontent.com/38470944/185069378-44d0ac7e-1f0d-48ea-8815-785bfdc9a269.jpg)

**To Reproduce**
tried to login with 3 different accounts all throws same error

**Expected behavior**
it should login

**Screenshots**
attached

**Smartphone (please complete the following information):**
 - Device: redmi note 10s
 - OS: 12 miui 13

**App**
- latest from playstore

**Comment by TheAlphamerc** [comment]
@HikaruIchijyo  Did you create the account in this app?

**Comment by HikaruIchijyo** [comment]
> @HikaruIchijyo  Did you create the account in this app?

ohk my bad i didnt i tried using twitter one

**Comment by HikaruIchijyo** [comment]
> @HikaruIchijyo  Did you create the account in this app?

i tried with name kirito

![IMG_20220817_155012.jpg](https://user-images.githubusercontent.com/38470944/185100903-0ad4b272-3d09-4700-88f8-280c2a051a74.jpg)

**Comment by HikaruIchijyo** [comment]
nvm it also got fixed by changing email address
