### ISSUE TITLE
NEW UPDATE

### ISSUE THREAD

**Issue by emiravdovic** [TheAlphamerc/flutter_twitter_clone#27]
The last update have problem, don't showing post on the feed page, also don't showing posts on the user profile, when post is created on the feed page is visible only some second und after this showing loading indicator und staying like this..

**Comment by TheAlphamerc** [comment]
@emiravdovic this is due to I have made some changes in notification, Following and Follower database schema. To sync with new database schema you need to clear your previous database from firebase.
> Please take a backup before clear database from firebase if it is important.

**Comment by emiravdovic** [comment]
> @emiravdovic this is due to I have made some changes in notification, Following and Follower database schema. To sync with new database schema you need to clear your previous database from firebase.
> 
> > Please take a backup before clear database from firebase if it is important.

aa okay I will try..

**Comment by emiravdovic** [comment]
Now work without problem... 👍👍👍👍👍  Will be nice if the user can login also with user name..

**Comment by TheAlphamerc** [comment]
Currently firebase has no such feature to login with username for.

**Comment by emiravdovic** [comment]
Is posible at least that users can have username without random text on the end... Something like this.. https://fireship.io/lessons/custom-usernames-with-firebase-authentication-and-angular/img/username.gif

   2-  https://fireship.io/lessons/custom-usernames-with-firebase-authentication-and-angular/

**Comment by TheAlphamerc** [comment]
Yes it is possible. Currently I am working on migrating app database from firebase `Realtime` to `Firestone`. Once it is fully migrated then it will be easier to check if given `username` is already taken by other user or not. 
Currently there is no separate table to save all `username` but after db migration I will create a separate table to save only `username`.
