### ISSUE TITLE
ios pod install error

### ISSUE THREAD

**Issue by superClown** [TheAlphamerc/flutter_twitter_clone#273]
hi，When I execute pod install, I receive the following error message. My current Ruby version is 3.0.0. Is it due to different versions of Ruby?

Invalid plugin specification: EXCLUDED_ARCHS[sdk=iphonesimulator*]=i386
Invalid plugin specification: EXCLUDED_ARCHS[sdk=iphoneos*]=armv7
Invalid plugin specification: DART_DEFINES=Zmx1dHRlci5pbnNwZWN0b3Iuc3RydWN0dXJlZEVycm9ycz10cnVl,RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ==

[!] Invalid `Podfile` file: no implicit conversion of nil into String.

 #  from /Users/kaka/open_sources/flutter_twitter_clone/ios/Podfile:57
 #  -------------------------------------------
 #      unless File.exist?(copied_framework_path)
 >        FileUtils.cp_r(File.join(cached_framework_dir, 'Flutter.framework'), copied_flutter_dir)
 #      end
 #  -------------------------------------------

**Comment by TheAlphamerc** [comment]
Can you try to remove podfile.lock and then try to install pods ?

**Comment by breezybaldwin** [comment]
Same error. Getting this still after removing the podfile.lock file

**Comment by superClown** [comment]
> Can you try to remove podfile.lock and then try to install pods ?
still the same error

MacBook-Pro ~/open_sources/flutter_twitter_clone/ios rm -rf Podfile.lock
MacBook-Pro ~/open_sources/flutter_twitter_clone/ios pod install
Invalid plugin specification: EXCLUDED_ARCHS[sdk=iphonesimulator*]=i386
Invalid plugin specification: EXCLUDED_ARCHS[sdk=iphoneos*]=armv7
Invalid plugin specification: DART_DEFINES=Zmx1dHRlci5pbnNwZWN0b3Iuc3RydWN0dXJlZEVycm9ycz10cnVl,RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ==

[!] Invalid `Podfile` file: no implicit conversion of nil into String.

 #  from /Users/kaka/open_sources/flutter_twitter_clone/ios/Podfile:57
 #  -------------------------------------------
 #      unless File.exist?(copied_framework_path)
 >        FileUtils.cp_r(File.join(cached_framework_dir, 'Flutter.framework'), copied_flutter_dir)
 #      end
 #  -------------------------------------------

**Comment by TheAlphamerc** [comment]
Ok, let's try to remove podfile and then run `flutter pub get` and ios `pod install`.

**Comment by superClown** [comment]
> Ok, let's try to remove podfile and then run `flutter pub get` and ios `pod install`.

It's work, thank you.
