### ISSUE TITLE
App not launching !

### ISSUE THREAD

**Issue by ErnestRobin** [TheAlphamerc/flutter_twitter_clone#276]
I was able to clone the project successfully and my development enveroment are flutter sdk 3.3.8, dart sdk 2.7.9. after building the project it failed to launch and keep crashing. please how can i migrate the current sdk though you recommend 2.10 which is not more available.
device use is Sumsang A23 series
Andriod 13

**Comment by TheAlphamerc** [comment]
@ErnestRobin I have updated the wiki regarding flutter version. The app is running fine on flutter version 3.3.8.
Please ensure that you have integrated firebase correctly. If still you are facing same issue please share console logs.
