### ISSUE TITLE
Missing Doc for RemoteConfig

### ISSUE THREAD

**Issue by ruepay** [TheAlphamerc/flutter_twitter_clone#28]
Hi there's no way to understand how you implemented firebase remote config.

**Comment by TheAlphamerc** [comment]
You can find bleow code on lib/state/chats/chatState.dart from line no 69.

![Remote-config](https://user-images.githubusercontent.com/37103237/80962483-bda99680-8e2a-11ea-8f9e-bf070ca879b1.png)

* Go to firebase remote config
* Create parameter with name `FcmServerKey` 
* Add below json to default value field.

 
`json
     {
          "key": "FCM server key here"
     } 
`

Check below firebase config screenshot

<img width="1245" alt="Screenshot 2020-05-04 at 5 18 04 PM" src="https://user-images.githubusercontent.com/37103237/80962801-5a6c3400-8e2b-11ea-933c-fa2673f4b2e4.png">

**Comment by gulmensedat** [comment]
I couldn't understand how to get the key

**Comment by TheAlphamerc** [comment]
Follow below steps to get FCM server key.
* Open your project in firebase.
* Click on gear icon in sidebar. A popup will open then click on` project settings`
<img width="496" alt="Screenshot 2020-05-04 at 6 01 40 PM" src="https://user-images.githubusercontent.com/37103237/80966654-8a6b0580-8e32-11ea-98e5-0b63d9941e5e.png">

* Open `Cloud messaging` tab
<img width="1079" alt="Screenshot 2020-05-04 at 6 02 00 PM" src="https://user-images.githubusercontent.com/37103237/80966704-a2db2000-8e32-11ea-92b2-d7c4e000e83e.png">

* You can get FCM server key from there
<img width="1484" alt="Screenshot 2020-05-04 at 6 02 18 PM" src="https://user-images.githubusercontent.com/37103237/80966746-b71f1d00-8e32-11ea-988f-fde0a5e35438.png">

**Comment by ruepay** [comment]
ok thanks .. awesome work by the way

**Comment by The3seus** [comment]
[getFCMServerKey] [Error]
                    "Please configure Remote config in firebase"

Everything has been configured still getting error been troubleshooting cant seem to figure why

**Comment by The3seus** [comment]
![Screenshot from 2020-07-29 01-23-35](https://user-images.githubusercontent.com/48400442/88760038-265a9380-d13a-11ea-9a06-757a6f5af955.png)

**Comment by The3seus** [comment]
![Screenshot from 2020-07-29 01-24-25](https://user-images.githubusercontent.com/48400442/88760098-468a5280-d13a-11ea-9f85-db1df6a55182.png)
