### ISSUE TITLE
Adding multiple languages

### ISSUE THREAD

**Issue by galibaaemree** [TheAlphamerc/flutter_twitter_clone#280]
Hello my friend, I noticed that there is no multi-language in the application, only English is available, how can I integrate multiple languages ​​into the application?

**Comment by galibaaemree** [comment]
May I know when the new update will come? and you can also change the application design with the current twitter design

**Comment by TheAlphamerc** [comment]
Hi @galibaaemree, Currently I have no plans for a future update.
