### ISSUE TITLE
failed to build app

### ISSUE THREAD

**Issue by rushilms** [TheAlphamerc/flutter_twitter_clone#281]
E:\twitterflugit\flutter_twitter_clone-master\flutter_twitter_clone-master\android\app\src\main\AndroidManifest.xml Error:
	Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> Manifest merger failed : Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 42s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by TheAlphamerc** [comment]
@rushilms am not able to reproduce the issue.

**Comment by rushilms** [comment]
> @rushilms am not able to reproduce the issue.

Have solved that for now, the  login is working. But can you help me with, the tweets. It goes to loading state as I try to tweet and I am not able to fetch old tweets

**Comment by TheAlphamerc** [comment]
Any log on console ?
