### ISSUE TITLE
Language issue

### ISSUE THREAD

**Issue by dextermax3** [TheAlphamerc/flutter_twitter_clone#282]
when i run the app for the first time in any deferent Language other than Eng, it gives me remote config error, but in English it works fine.

**Comment by TheAlphamerc** [comment]
@dextermax3 Can you share console logs ?

**Comment by dextermax3** [comment]
![Untitledddd](https://user-images.githubusercontent.com/105817000/212615652-592b7236-7f74-446b-952e-e878b0847827.jpg)

**Comment by TheAlphamerc** [comment]
@dextermax3 what error you are getting ?

**Comment by dextermax3** [comment]
@TheAlphamerc  the app work fine in English devices (but Arabic language devices show the below error 
![fwitterpic](https://user-images.githubusercontent.com/105817000/212698545-92136ba2-5cf2-4f2c-b688-cde952817c72.jpg)

**Comment by TheAlphamerc** [comment]
@dextermax3 it is hard to tell what's the issue without checking the code.

**Comment by dextermax3** [comment]
@TheAlphamerc thanks for this great app anyway :)

**Comment by dextermax3** [comment]
@TheAlphamerc here's the code, should i put the key pair 
![Untitledfcm](https://user-images.githubusercontent.com/105817000/212926317-9cded24f-ca00-4026-b754-85415b2c61a5.png)
as pic

**Comment by dextermax3** [comment]
@TheAlphamerc bro it was a bug from my pc, the app work fine .
