### ISSUE TITLE
can i take alook at your messaging at firebase

### ISSUE THREAD

**Issue by dextermax3** [TheAlphamerc/flutter_twitter_clone#286]
hello sonu,
i got the below messaging at firebase console but the push notification didn't showing
![Untitledffffd](https://user-images.githubusercontent.com/105817000/215290797-fe89b082-b5a4-4123-83fb-b730acbab809.jpg)

**Comment by TheAlphamerc** [comment]
@dextermax3 it is an optional field you don't need to add fcmServerKey here.
<img width="923" alt="Screenshot 2023-01-29 at 2 56 27 AM" src="https://user-images.githubusercontent.com/37103237/215291936-3969d9b9-4a36-4783-974f-fbec414cdff7.png">

**Comment by dextermax3** [comment]
so the notification didn't showing, what should i do?

**Comment by TheAlphamerc** [comment]
@dextermax3 in that case check firebase is configured correctly. If it is done then try solution mentioned here -> https://stackoverflow.com/a/54490885/9390431

**Comment by dextermax3** [comment]
@TheAlphamerc thanks for your help,
i just stuck in here, don't know how to get fcmToken and add it here (to"")
![iou](https://user-images.githubusercontent.com/105817000/215347952-b06d0c2f-a842-48e5-acf1-49d77f7daff9.jpg)

**Comment by TheAlphamerc** [comment]
You can get fcmToken using firebase_messaging plugin. Check documentation here -> https://firebase.flutter.dev/docs/messaging/usage#web-tokens
![Screenshot 2023-01-30 at 9 56 40 AM](https://user-images.githubusercontent.com/37103237/215387471-86080f7f-74b3-4487-97d9-55cd419c49c5.png)
