### ISSUE TITLE
I can't build

### ISSUE THREAD

**Issue by gongapin** [TheAlphamerc/flutter_twitter_clone#290]
when i build it show error

Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by RedTomatoCat** [comment]
- - look this
 -Try:
Run with --stacktrace option to get the stack trace. **Run with --info or --debug** option to get more log output. Run with --scan to get full insights.

your can,click run with --info or debug, check this err .....

**Comment by TheAlphamerc** [comment]
Looks like the issue is related to some cache. Try `flutter clean` and `flutter pub get`. It will resolve the issue.
