### ISSUE TITLE
I cant build due to Google Services

### ISSUE THREAD

**Issue by Ugocode** [TheAlphamerc/flutter_twitter_clone#299]
I cant build the app on my system so I can contribute to this open source

The Error: 
What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 

Do I need to Setup the project on Firebase for me to be able to build the project on my system?

**Comment by Ugocode** [comment]
Okay fixed. I had to register the app on Firebase and configured all the necessary settings to build the app

**Comment by Ugocode** [comment]
Okay fixed. I had to register the app on Firebase and configured all the necessary settings to build the app

So Closed

**Comment by mohitdebian** [comment]
> 
> I cant build the app on my system so I can contribute to this open source
> 
> The Error: 
> What went wrong:
> Execution failed for task ':app:processDebugGoogleServices'.
> > File google-services.json is missing. The Google Services Plugin cannot function without it. 
> 
> 
> Do I need to Setup the project on Firebase for me to be able to build the project on my system?

Bruh 😮‍💨 you can't even resolve this type of error. Before making a issue ob github you should check it on google 🙄
