### ISSUE TITLE
Flutter Update

### ISSUE THREAD

**Issue by ruepay** [TheAlphamerc/flutter_twitter_clone#30]
Just updated my flutter version and error popped up in "customRoute.dart "
This is the i am getting as of now :
"The getter 'isInitialRoute' isn't defined for the type 'RouteSettings'.
Try importing the library that defines 'isInitialRoute', correcting the name to the name of an existing getter, or defining a getter or field named 'isInitialRoute'."
Please check and let me know if the error is universal.

**Comment by TheAlphamerc** [comment]
Try removing or comment out code where `isInitialRoute` is used in CustomRoute.dart file.
CustomRoute class can be found at `lib/helper/customRoute.dart` location.

<img width="1020" alt="Screenshot 2020-05-10 at 6 25 28 PM" src="https://user-images.githubusercontent.com/37103237/81499827-debb2d00-92eb-11ea-98f8-a069b0bfb188.png">
