### ISSUE TITLE
sign Up is not working

### ISSUE THREAD

**Issue by mummurthig** [TheAlphamerc/flutter_twitter_clone#31]
when i click sign up button it's showing this error  

MissingPluginException(No implementation found for method createUserWithEmailAndPassword on channel plugins.flutter.io/firebase_...

 Unable to login
![WhatsApp Image 2020-05-07 at 4 03 57 PM](https://user-images.githubusercontent.com/60460387/81285275-e759fc00-907c-11ea-9f38-e0edf2a9357f.jpeg)

**Comment by TheAlphamerc** [comment]
You have to enable `Email/Password` login  in firebase

<img width="1150" alt="Screenshot 2020-05-07 at 7 51 14 PM" src="https://user-images.githubusercontent.com/37103237/81305766-585cdc00-909c-11ea-9ff9-05ae8679580c.png">

**Comment by mummurthig** [comment]
Thank you
