### ISSUE TITLE
Follow button Bug

### ISSUE THREAD

**Issue by RashoAli** [TheAlphamerc/flutter_twitter_clone#33]
**Describe the bug**
when pressing the follow button the button stay gray and im geting the following error

════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
Tried to listen to a value exposed with provider, from outside of the widget tree.

This is likely caused by an event handler (like a button's onPressed) that called
Provider.of without passing `listen: false`.

To fix, write:
Provider.of<NotificationState>(context, listen: false);

It is unsupported because may pointlessly rebuild the widget associated to the
event handler, when the widget tree doesn't care about the value.

The context used was: HomePage(dependencies: [_InheritedProviderScope<AppState>], state: _HomePageState#72bcb)
'package:provider/src/provider.dart':
Failed assertion: line 191 pos 7: 'context.owner.debugBuilding ||
          listen == false ||
          debugIsInInheritedProviderUpdate'

When the exception was thrown, this was the stack: 
#2      Provider.of (package:provider/src/provider.dart:191:7)
#3      _HomePageState._checkNotification.<anonymous closure> (package:flutter_twitter_clone/page/homePage.dart:86:28)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
#5      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1060:9)
#6      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:968:5)
...

**Comment by Curiosity324** [comment]
You need to downgrade provider to provider: ^3.0.3
