### ISSUE TITLE
INVALID_KEY

### ISSUE THREAD

**Issue by adna2331** [TheAlphamerc/flutter_twitter_clone#35]
flutter: DBnbjTIRahTGFXBDItGEkpbRKFJ2
flutter: [EVENT]: send_message
flutter: Settings registered: PushNotificationSettings {sound: true, alert: true, badge: true, provisional: false}
flutter: <HTML>
<HEAD>
<TITLE>INVALID_KEY</TITLE> 
</HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000">
<H1>INVALID_KEY</H1>
<H2>Error 401</H2>
</BODY>
</HTML>

 Where can I put this key?
I puted already in chatState.dart  the serverToken key but i don't receiving notification when I send message with phone, but when I send with firebase I receiving.

**Comment by TheAlphamerc** [comment]
You can see detailed discussion here:- https://github.com/TheAlphamerc/flutter_twitter_clone/issues/28#issue-611695533

**Comment by adna2331** [comment]
I set everything up like that, but error is still there..

![Screenshot 2020-05-14 at 16 53 12](https://user-images.githubusercontent.com/65310906/81952306-9ca12c80-9606-11ea-960e-7fbc72e76d3e.png)
![Screenshot 2020-05-14 at 16 51 43](https://user-images.githubusercontent.com/65310906/81952320-9e6af000-9606-11ea-9bf5-e2232557312e.png)

**Comment by adna2331** [comment]
![Screenshot 2020-05-14 at 17 17 05](https://user-images.githubusercontent.com/65310906/81952453-cb1f0780-9606-11ea-9816-6f5741ee53cb.png)

**Comment by TheAlphamerc** [comment]
According to the console log the FCM key you are using is not correct. Please verify the key again.

**Comment by TheAlphamerc** [comment]
The error you are getting because you have changed `getFCMServerKey`method.
<img width="1082" alt="Screenshot 2020-05-14 at 9 20 47 PM" src="https://user-images.githubusercontent.com/37103237/81956846-6de87d80-9629-11ea-8ec2-42ec39ce3581.png">

**Comment by adna2331** [comment]
I will try now, I think this was problem bc don't showing errors now. but I will try..

**Comment by adna2331** [comment]
Thanks, now working. 👍 👍 👍

**Comment by adna2331** [comment]
Can I also make bottom navigation bar bar to be visible on the profile page, to look similar with the real twitter.. Thank you so much..

**Comment by TheAlphamerc** [comment]
There isn't any bottom navigation bar on profile page in twitter app.

**Comment by adna2331** [comment]
Like this, i mean already have on the feedpage, notification, messages und search. But don't have on the profile page  und page of users. 

![WhatsApp Image 2020-05-15 at 00 04 18](https://user-images.githubusercontent.com/65310906/81990828-36390000-9640-11ea-99d9-a5a9e7ca66c0.jpeg)
