### ISSUE TITLE
Please update the readme file

### ISSUE THREAD

**Issue by postacik** [TheAlphamerc/flutter_twitter_clone#37]
Thanks for this great project. :)

I had problems while running the app in my development environment because the "Getting started" instructions are not up to date.

I think the readme file needs two updates:

1. Add "Storage" to your Firebase project (otherwise storing images do not work)
2. Add "FcmServerKey" to Firebase Remote Config

**Comment by Deepankar1999** [comment]
Can you please describe step 2 briefly ?

**Comment by TheAlphamerc** [comment]
@Deepankar1999 you can check detail description about `FcmServerKey` at https://github.com/TheAlphamerc/flutter_twitter_clone/issues/28#issuecomment-623419343

**Comment by postacik** [comment]
Please pay attention to the following misleading instruction:
Add below json to default value field.
`json { "key": "FCM server key here" }`

You should set the value without the json word at the beginning as can be seen below:
`{ "key": "FCM server key here" }`

Maybe it's trivial but if you blindly copying and pasting, it may fail you.

**Comment by TheAlphamerc** [comment]
Thanks @postacik  for letting me know. I have fixed this.

**Comment by Deepankar1999** [comment]
> @Deepankar1999 you can check detail description about `FcmServerKey` at [#28 (comment)](https://github.com/TheAlphamerc/flutter_twitter_clone/issues/28#issuecomment-623419343)

Thanks @TheAlphamerc

**Comment by asopiah** [comment]
NB: In dev env it's key to change duration to 0 for making sure it fetches from the remote config immediately i.e change  `await remoteConfig.fetch(expiration: const Duration(hours: 5));` to  `await remoteConfig.fetch(expiration: const Duration(seconds: 0));`
