### ISSUE TITLE
SliverList / grid help

### ISSUE THREAD

**Issue by kerem-eng** [TheAlphamerc/flutter_twitter_clone#38]
How can i implement one more option on "Profile page"  for users witch want to switch  the view from "sliverList" to "SliverGrid"  is this possible?

<img width="219" alt="grid list image" src="https://user-images.githubusercontent.com/65556239/82234778-210aec80-9932-11ea-86a3-7357bd686a93.png">

![0*0ODx0tDYSC4wSGYM](https://user-images.githubusercontent.com/65556239/82235498-0dac5100-9933-11ea-817c-18b06c74d804.png)

Thank you so much! Very good project 👍

**Comment by TheAlphamerc** [comment]
Flutter provides several widgets and methods to implement this structure. You can use `GridView` widget to create this type of grid.
For more info look at https://flutter.dev/docs/cookbook/lists/grid-lists

**Comment by kerem-eng** [comment]
Thank you, with this edit the grid is visible. But what elese to change to grid showing my posted pictures .
![Uploading Screenshot 2020-05-19 at 00.59.46.png…]()

![IMG_0001](https://user-images.githubusercontent.com/65556239/82267624-36513c80-996d-11ea-8eae-a9f20a6bd8fc.png)

**Comment by kerem-eng** [comment]
Thank you, with this edit the grid is visible. But what elese to change to grid showing my posted pictures. 
![Screenshot 2020-05-19 at 00 59 46](https://user-images.githubusercontent.com/65556239/82267697-64368100-996d-11ea-8341-0a5625318be6.png)
![IMG_0001](https://user-images.githubusercontent.com/65556239/82267714-6993cb80-996d-11ea-9bbd-cfb44a5fee58.png)

**Comment by kerem-eng** [comment]
Thank you, with this edit the grid is visible. But what else to change to grid showing my posted pictures.  

![82267697-64368100-996d-11ea-8341-0a5625318be6](https://user-images.githubusercontent.com/65556239/82382587-8511db80-9a2c-11ea-9c51-ea35018b43f1.png)

![82267714-6993cb80-996d-11ea-9bbd-cfb44a5fee58](https://user-images.githubusercontent.com/65556239/82382602-893df900-9a2c-11ea-83bf-6433b87738c5.png)

**Comment by ahmad210** [comment]
I am also curious how to make this?  o.O

**Comment by ahmad210** [comment]
I am also curious how to make this? o.O

**Comment by kerem-eng** [comment]
Help please? 👍

**Comment by kerem-eng** [comment]
Help please?

![Screenshot 2020-05-30 at 23 22 20](https://user-images.githubusercontent.com/65556239/83339277-7a790100-a2cc-11ea-8be7-acb561c3e4f3.png)

**Comment by kerem-eng** [comment]
With this edit the grid shows the posts but in each box it shows the list the same as on the feed page, how can I make the grid show each image separately?

![Screenshot 2020-05-31 at 01 13 36](https://user-images.githubusercontent.com/65556239/83340783-a1d7ca00-a2dc-11ea-8123-c778fc8a57df.png)

**Comment by kerem-eng** [comment]
children:   ?  Thanks..
 

 GridView.count(
                          crossAxisCount: 3,
                          childAspectRatio: 1.0,
          //                    padding: const EdgeInsets.all(0.5),
                          mainAxisSpacing: 1.5,
                          crossAxisSpacing: 1.5,
                          shrinkWrap: true,
                          physics: const NeverScrollableScrollPhysics(),
                        children:  
                    
                ),
