### ISSUE TITLE
Error with uploading tweets(AppMeasurementReceiver not enabled) and error with AndroidManifest.xml.

### ISSUE THREAD

**Issue by Deepankar1999** [TheAlphamerc/flutter_twitter_clone#41]
I am having error while uploading tweets it shows error AppMeasurementReciever not enabled.
![Screenshot (5)](https://user-images.githubusercontent.com/46363338/83170170-be83ce80-a131-11ea-86f3-e66749ac8ac1.png)

Then added following codes in android/app/src/main/AndroidManifest.xml .
![Screenshot (8)](https://user-images.githubusercontent.com/46363338/83170448-2cc89100-a132-11ea-9967-1f17337e2087.png)

And i am getting the following error in my AndroidManifest.xml
![Screenshot (7)](https://user-images.githubusercontent.com/46363338/83170626-787b3a80-a132-11ea-938d-647e39da6c93.png)

Can anyone help me with this issue. @TheAlphamerc can you please guide .

**Comment by TheAlphamerc** [comment]
@Deepankar1999 which branch you are using?. Have you enabled firebase database?

**Comment by Deepankar1999** [comment]
> @Deepankar1999 which branch you are using?. Have you enabled firebase database?

I am using the master branch and yes I have enabled firebase database.

**Comment by Deepankar1999** [comment]
I also have followed every procedure given in readme plus also added the fcmserverkey. Still I am getting these errors🙁

**Comment by TheAlphamerc** [comment]
Have you enable enabled firebase Analytics?

**Comment by Deepankar1999** [comment]
> Have you enabled firebase Analytics and firebase storage?

Yeah done that also.

**Comment by TheAlphamerc** [comment]
Try with remove code that you have added in AndroidManifest.xml and create a new project in firebase by following getting started steps.

**Comment by Deepankar1999** [comment]
> Try with remove code that you have added in AndroidManifest.xml and create a new project in firebase by following getting started steps.

Thanks @TheAlphamerc , the app works perfectly fine now.
