### ISSUE TITLE
Firestore database

### ISSUE THREAD

**Issue by thierry-tct** [TheAlphamerc/flutter_twitter_clone#43]
Is there a way to easily get the database model for the Firestore branch?

I saw the Collection names in the file [lib/helper/constant.dart](lib/helper/constant.dart). However, It is not clear which Collection corresponds to which model.

**Comment by TheAlphamerc** [comment]
Store `List` of [User](https://github.com/TheAlphamerc/flutter_twitter_clone/blob/master/lib/model/user.dart) Model in db
```dart
const String USERS_COLLECTION = "profile";
```

 Store `List` of [`FeedModel`](https://github.com/TheAlphamerc/flutter_twitter_clone/blob/master/lib/model/feedModel.dart) Model in db
```dart
const String TWEET_COLLECTION = "tweet";
```

 Store `List` of [`ChatMessage`](https://github.com/TheAlphamerc/flutter_twitter_clone/blob/master/lib/model/chatModel.dart) Model in db
```dart
const String MESSAGES_COLLECTION = "messages";
```

 Store `List` of [`ChatMessage`](https://github.com/TheAlphamerc/flutter_twitter_clone/blob/master/lib/model/chatModel.dart) Model in db
`chatUsers` are stored in `ChatMessage` on purpose
```dart
const String CHAT_USER_LIST_COLLECTION = "chatUsers";
```

 Store [`NotificationModel`](https://github.com/TheAlphamerc/flutter_twitter_clone/blob/master/lib/model/notificationModel.dart) Model in db
```dart
const String NOTIFICATION_COLLECTION = "notification";
```

**Comment by thierry-tct** [comment]
Many Thanks!

Great work
