### ISSUE TITLE
Swipe indicator (iphone x and up) 

### ISSUE THREAD

**Issue by qwerty684** [TheAlphamerc/flutter_twitter_clone#45]
Can we make that bottom menu bar recognise iOS devices with swipe indicator and automatically move bottom bar up?

![Screenshot 2020-06-06 at 21 16 23](https://user-images.githubusercontent.com/53181006/83952870-638e5d80-a83c-11ea-92f2-04c8bbf388cb.png)
 
![IMG_4791](https://user-images.githubusercontent.com/53181006/83952874-68eba800-a83c-11ea-89fa-c0f5cc8adfcd.jpg)

**Comment by DebugHer** [comment]
Just wrap with safe area widget and you should be fine
