### ISSUE TITLE
Follow button is not working.

### ISSUE THREAD

**Issue by Deepankar1999** [TheAlphamerc/flutter_twitter_clone#46]
While I was running the app in my device i got some serious issues ,the follow button is not working.

The error was shown:-
Tried to listen to a value exposed with provider, from outside of the widget tree.

This is likely caused by an event handler (like a button's onPressed) that called
Provider.of without passing `listen: false`.

To fix, write:
Provider.of<NotificationState>(context, listen: false);

It is unsupported because may pointlessly rebuild the widget associated to the
event handler, when the widget tree doesn't care about the value.

The context used was: HomePage(dependencies: [_InheritedProviderScope<AppState>], state: _HomePageState#c80e8)
'package:provider/src/provider.dart':
Failed assertion: line 191 pos 7: 'context.owner.debugBuilding ||
          listen == false ||
          debugIsInInheritedProviderUpdate'

Can anybody help me how can i solve this issue .

**Comment by Deepankar1999** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/46363338/83971625-0658e180-a8fa-11ea-8252-0e44707c76f5.gif)
![Screenshot (10)](https://user-images.githubusercontent.com/46363338/83971667-18d31b00-a8fa-11ea-8298-d5090c855c3c.png)
here are the screenshots.

**Comment by Deepankar1999** [comment]
@TheAlphamerc can you please guide me through this error.

**Comment by TheAlphamerc** [comment]
@Deepankar1999 Please try following steps:-
* Open [ProfilePage](https://github.com/TheAlphamerc/flutter_twitter_clone/blob/master/lib/page/profile/profilePage.dart)
* Search for `isFollower()` method
* Add ` listen:false` in authstate provider.

<img width="1194" alt="Screenshot 2020-06-07 at 8 26 09 PM" src="https://user-images.githubusercontent.com/37103237/83972378-75840500-a8fd-11ea-932b-7378bd03e55e.png">

Let me know if you still face this error.

**Comment by Deepankar1999** [comment]
Thanks now the app works perfectly fine 👌
