### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by Alsuhaibani** [TheAlphamerc/flutter_twitter_clone#49]
**Hi Sonu Sharma** 
i hope you doing well

in searchState i get this error under (kDatabase.child('profile').once().then) :
"Exception has occurred.
DatabaseError (DatabaseError(-3, Permission denied, ))"

I check on my database Rules    ( allow read,  allow write)
I don't know where the error is..

**Comment by TheAlphamerc** [comment]
Usually this error occurred due to database rules restriction. I suggest you to check all configurations once again.

**Comment by TheAlphamerc** [comment]
Closing this issue for now. If you still facing this error feel free to open the issue.
