### ISSUE TITLE
GoogleServiceProblem

### ISSUE THREAD

**Issue by gulmensedat** [TheAlphamerc/flutter_twitter_clone#50]
Do you have any idea that I could not understand the problem?

Plugin project :firebase_core_web not found. Please update settings.gradle.
Plugin project :cloud_firestore_web not found. Please update settings.gradle.
Plugin project :firebase_auth_web not found. Please update settings.gradle.
Plugin project :url_launcher_web not found. Please update settings.gradle.

FAILURE: Build failed with an exception.

**Comment by TheAlphamerc** [comment]
Make sure you have followed [Getting Started](https://github.com/TheAlphamerc/flutter_twitter_clone/wiki/Gettings-Started) instruction. If you skip any step then it might create problem to run project.

**Comment by TheAlphamerc** [comment]
@gulmensedat have to checked that you have added google-service.json file in `/android/app/` path?

**Comment by gulmensedat** [comment]
yes there is, it works firebase.

**Comment by TheAlphamerc** [comment]
@gulmensedat your issue resolved?

**Comment by gulmensedat** [comment]
> your issue resolved?

I'm just getting logs. Practically no problem appears.
