### ISSUE TITLE
how possible to merge a video uploader and player with fwitter project?

### ISSUE THREAD

**Issue by bendev101** [TheAlphamerc/flutter_twitter_clone#51]
hi sonu, can you please share your business contact details.

**Comment by TheAlphamerc** [comment]
Hi @bendev101, Please describe the feature in more detail?

**Comment by bendev101** [comment]
can you please delete this issue, I'm opening a new one right now

**Comment by TheAlphamerc** [comment]
The delete option is not available. Let me close this.
