### ISSUE TITLE
video uploader and player with multiple images selection

### ISSUE THREAD

**Issue by bendev101** [TheAlphamerc/flutter_twitter_clone#52]
how possible to add a video picker function in"composeBottomIconWidget" and video player in "feedpage"? along with your current image posting.
also is there a possibility for multiple image selection without changing image_picker with multi_media_picker plugin?
thank you

**Comment by bendev101** [comment]
Can you please give us your thoughts?

**Comment by TheAlphamerc** [comment]
@bendev101 I think these two links may help you. Please have a look.

[Pick video](https://medium.com/@KarthikPonnam/image-video-picker-flutter-1222f3764da9)

[Upload video to firebase](https://stackoverflow.com/questions/51822789/flutter-firebase-storage-upload-video)

**Comment by bendev101** [comment]
thank you
