### ISSUE TITLE
Tag people error

### ISSUE THREAD

**Issue by kerem-eng** [TheAlphamerc/flutter_twitter_clone#53]
Hello, 

I using firestore database version of app, and for some reason don't work tag people option, 
when I make @test         this show me list of users, but when I tape on user this don't want to add      _________________ @test
this user. show error.

flutter: Another exception was thrown: Tried to listen to a value exposed with provider, from outside of the widget tree.

Thanks.

**Comment by TheAlphamerc** [comment]
@kerem-eng  Please share error log screenshot.

**Comment by kerem-eng** [comment]
@TheAlphamerc 

![Screenshot 2020-06-24 at 17 24 24](https://user-images.githubusercontent.com/65556239/85585002-edf9fe00-b63f-11ea-9567-dd15718e9d9f.png)

**Comment by TheAlphamerc** [comment]
@kerem-eng I have checked this scenario and I am not able to produce this error. Please make sure you are using latest code and the latest version of flutter SDK.

**Comment by kerem-eng** [comment]
@TheAlphamerc  I have video here.

 https://vimeo.com/user118342339/review/432208266/1841ad2b19

**Comment by TheAlphamerc** [comment]
@kerem-eng Video link is not opening.

**Comment by kerem-eng** [comment]
Here is other..
https://streamable.com/7a2l0u
