### ISSUE TITLE
Provider Error

### ISSUE THREAD

**Issue by gulmensedat** [TheAlphamerc/flutter_twitter_clone#56]
The problem was solved by reducing the provider package before, but a newly written package that I use is failing because it does not fit the low provider package. How can I solve this error without getting the provider down?

And in profilePage var authstate = Provider.of <AuthState> (context, listen: false); I did

```
The following assertion was thrown during a scheduler callback:
Tried to listen to a value exposed with provider, from outside of the widget tree.

This is likely caused by an event handler (like a button's onPressed) that called
Provider.of without passing `listen: false`.

To fix, write:
Provider.of<NotificationState>(context, listen: false);

It is unsupported because may pointlessly rebuild the widget associated to the
event handler, when the widget tree doesn't care about the value.

The context used was: HomePage(dependencies: [_InheritedProviderScope<AppState>], state: _HomePageState#bf130)
'package:provider/src/provider.dart':
Failed assertion: line 191 pos 7: 'context.owner.debugBuilding ||
          listen == false ||
          debugIsInInheritedProviderUpdate'

```

**Comment by TheAlphamerc** [comment]
This error is occurring in new version of provider package. To avoid this error add `listen:false` in provider.

**Comment by amraza01** [comment]
I'm sorry, I am new to all of this, where exactly do I add `listen:false` in provider? Do I replace listen == false in the failed assertion line? or do I need to add it as another condition to that line? or do i add it somewhere else entirely? Thanks!

**Comment by TheAlphamerc** [comment]
@amraza01 if you're facing this error on profile page then replace `Provider.of<NotificationState>(context);` by `Provider.of<NotificationState>(context, listen: false);`

**Comment by amraza01** [comment]
Thank you! I had to make this change once on the home page and on 2 lines of the search page for it to run with no errors
