### ISSUE TITLE
Google sign in Android

### ISSUE THREAD

**Issue by emiravdovic** [TheAlphamerc/flutter_twitter_clone#57]
I have this error when I try to create account with google on Android device, on iOS work properly.

![Screenshot 2020-07-08 at 18 20 14](https://user-images.githubusercontent.com/53181006/86944693-61276800-c148-11ea-97df-0fa5e6ceca1e.png)

**Comment by TheAlphamerc** [comment]
@emiravdovic this platform exception has occurred if you cancel the google login.

**Comment by emiravdovic** [comment]
@TheAlphamerc I don't canceling process , here is video ..

https://streamable.com/0ojh4k

**Comment by srthkpthk** [comment]
@emiravdovic please check sha1 in your project
