### ISSUE TITLE
Chat list sorted by last message

### ISSUE THREAD

**Issue by Asasapatata** [TheAlphamerc/flutter_twitter_clone#58]
Hello,
really nice job, congratulations!

What do you think about the sorting of the chat list? Now they are sorted by users, not by last message. How would you implement a chat list sorting by last message?

**Comment by TheAlphamerc** [comment]
@Asasapatata Please let me know which branch you are using?

**Comment by kerem-eng** [comment]
> @Asasapatata Please let me know which branch you are using?
@TheAlphamerc 
Can this work also on Firestore branch?

**Comment by TheAlphamerc** [comment]
Yes

**Comment by kerem-eng** [comment]
> Yes

Where need to be replaced, bc is difrent code, and have chatState and chatUserState

**Comment by kerem-eng** [comment]
> Yes

@TheAlphamerc 
Where need to be replaced, bc is difrent code, and have chatState and chatUserState?

**Comment by TheAlphamerc** [comment]
In chatUserState file search for 'getUserList' method. You can sort user list from this method.

**Comment by kerem-eng** [comment]
like this is still same, 
![Screenshot 2020-07-17 at 18 06 58](https://user-images.githubusercontent.com/65556239/87808061-688df600-c859-11ea-9a2c-52183c05b8f7.png)

**Comment by kerem-eng** [comment]
@TheAlphamerc  Like this is still same.

![Screenshot 2020-07-17 at 18 06 58](https://user-images.githubusercontent.com/65556239/87808200-98d59480-c859-11ea-858e-b9ad8c31d8fd.png)

**Comment by kerem-eng** [comment]
> @TheAlphamerc Like this is still same.
> 
> ![Screenshot 2020-07-17 at 18 06 58](https://user-images.githubusercontent.com/65556239/87808200-98d59480-c859-11ea-858e-b9ad8c31d8fd.png)

working after Restart app.. 👍
