### ISSUE TITLE
Icon badge for new notification or message or post

### ISSUE THREAD

**Issue by NoviSad557** [TheAlphamerc/flutter_twitter_clone#59]
can we expect badge on icons something like this

![badges](https://user-images.githubusercontent.com/65556239/87693606-7aa26280-c78d-11ea-97c8-02db2bda7a4f.jpg)

**Comment by TheAlphamerc** [comment]
Please explain on which icons you expect these badge.

**Comment by kerem-eng** [comment]
If someone sends me a message that I saw the icon on the message icon, otherwise I will not know that someone sent, or also for the notification icon..

**Comment by kerem-eng** [comment]
@TheAlphamerc 

https://pub.dev/packages/badges

![Screenshot 2020-07-19 at 20 56 03](https://user-images.githubusercontent.com/65556239/87882712-556a5a00-ca02-11ea-8230-bc26bf3d6729.png)

**Comment by TheAlphamerc** [comment]
@kerem-eng Noted. Will work on this feature soon.
