### ISSUE TITLE
Username

### ISSUE THREAD

**Issue by ifiy** [TheAlphamerc/flutter_twitter_clone#62]
Please, is it possible to change username once you sign up?

**Comment by TheAlphamerc** [comment]
@ifiy yes it is possible. To implement this you have to create a new `userName` table in database and at the time of signup save new username in `userName` table.
Once user successfully able to create his account then you can give him option to update his username in his profile page.
Ask user to enter new username, once user submitted a new username check `userName` db table if this name is already existed or not. If username not available in the database then you can update his username and save it to user profile.

**Comment by ifiy** [comment]
Thank you
