### ISSUE TITLE
Migrate firebase databse to MySQL

### ISSUE THREAD

**Issue by PujanModha** [TheAlphamerc/flutter_twitter_clone#64]
Hi,
I'm very impressed by your work, but i think there is some more features that you can add to this project : 
1. File Sharing In Chat
2. Audio And Video Calling In Chat
3. Instead Of Using Firebase Use My SQL (If Possible)
4. Admin Must Deserves More Rights
#. Please release separated version of chats (Request)

**Comment by TheAlphamerc** [comment]
Hi @PujanModha, Please check the below points and respond.

1. Will be added in new features.
2. Audio and Video calling will be included later in a future release.
3. Use of MySQL is not feasible now.
4. There is no admin functionality available right now. To develop this functionality It required admin panel at the backend so I will needs some help.
#. Did you mean to say release new chat app separately which contains these above functionality?

**Comment by PujanModha** [comment]
#. Basically I Mean That Can You Make WhatsApp Clone, Because I Seen Many Clones Of Various Apps But I'm Very Impressed By This Fwitter Clone. So I Think That You Can Make WhatsApp Clone ( Like JioChat [ LOL ] ).

**Comment by PujanModha** [comment]
3. (https://medium.com/@dev_raushanjha/sendhow-to-send-data-from-flutter-app-to-mysql-database-8e79844fc234)
And (https://pub.dev/packages/mysql1) Just For Reference.

**Comment by TheAlphamerc** [comment]
> #. Basically I Mean That Can You Make WhatsApp Clone, Because I Seen Many Clones Of Various Apps But I'm Very Impressed By This Fwitter Clone. So I Think That You Can Make WhatsApp Clone ( Like JioChat [ LOL ] ).

Ok, I will create a project on this soon.

**Comment by TheAlphamerc** [comment]
> 1. (https://medium.com/@dev_raushanjha/sendhow-to-send-data-from-flutter-app-to-mysql-database-8e79844fc234)
>    And (https://pub.dev/packages/mysql1) Just For Reference.

I understand what you are trying to say. To migrate app from firebase sb to MySQL a server is required.

**Comment by PujanModha** [comment]
> 
> 
> > #. Basically I Mean That Can You Make WhatsApp Clone, Because I Seen Many Clones Of Various Apps But I'm Very Impressed By This Fwitter Clone. So I Think That You Can Make WhatsApp Clone ( Like JioChat [ LOL ] ).
> 
> Ok, I will create a project on this soon.

Thanks.

**Comment by PujanModha** [comment]
> 
> 
> > 1. (https://medium.com/@dev_raushanjha/sendhow-to-send-data-from-flutter-app-to-mysql-database-8e79844fc234)
> >    And (https://pub.dev/packages/mysql1) Just For Reference.
> 
> I understand what you are trying to say. To migrate app from firebase sb to MySQL a server is required.

Exactly, For admin panel we must need a website as backend.

**Comment by TheAlphamerc** [comment]
Migrating database from firebase db to MySql is out of scope for this project so I am closing this issue.
