### ISSUE TITLE
Sort comment In details page, last comment to be on top..

### ISSUE THREAD

**Issue by NoviSad557** [TheAlphamerc/flutter_twitter_clone#65]
Sort comment In details page, last comment to be on top..

**Comment by TheAlphamerc** [comment]
@NoviSad557 Currently comment section showing two behavior.

- When users create new comment it is added at the end of the list [Need to modify].

- After opening tweet detail all comments are displayed in sorted order [Last comment on top].

This issue will be fixed soon.
