### ISSUE TITLE
This application cannot tree shake icons fonts. It has non-constant instances of IconData

### ISSUE THREAD

**Issue by rahulgurujala** [TheAlphamerc/flutter_twitter_clone#68]
**Tree shake icons fonts**

While Building an app I'm getting following errors :(

> This application cannot tree shake icons fonts. It has non-constant instances of IconData at the following locations:
>   - file:///C:/flutter_twitter_clone-master/lib/page/profile/profilePage.dart:168:43
>   - file:///C:/flutter_twitter_clone-master/lib/widgets/customWidgets.dart:70:7
> 
> 
> `Target aot_android_asset_bundle failed: Exception: Avoid non-constant invocations of IconData or try to build again with --no-tree-shake-icons.`
> build failed.
> FAILURE: Build failed with an exception.
> 
> * Where:
> Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 896
> 
> * What went wrong:
> Execution failed for task ':app:compileFlutterBuildRelease'.
> > Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1
> 
> * Try:
> `Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.`
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 2m 14s
> Running Gradle task 'assembleRelease'...                          136.3s (!)
> Gradle task assembleRelease failed with exit code 1
> Process finished with exit code 1

I search on Google as well as on StackOverflow but found nothing. It must be a bug which is in the project or maybe I'm doing something wrong.

**My IDE configuration is as follow**

> Android Studio 4.0
> Build #AI-193.6911.18.40.6514223, built on May 20, 2020
> Runtime version: 1.8.0_242-release-1644-b01 amd64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> Windows 10 10.0
> GC: ParNew, ConcurrentMarkSweep
> Memory: 2014M
> Cores: 4
> Registry: ide.new.welcome.screen.force=true
> Non-Bundled Plugins: Dart, org.jetbrains.kotlin, com.google.services.firebase, com.intellij.marketplace, com.thoughtworks.gauge, io.flutter, org.intellij.plugins.markdown

**JAVA configuration as follow**

> jdk1.8.0_261
> jre1.8.0_261
> jdk-11 (JDK 11 is my JAVA_HOME in environment variable)

**Comment by TheAlphamerc** [comment]
@rahulgurujala Please try after running `flutter clean` command.

**Comment by rahulgurujala** [comment]
No Mr. @TheAlphamerc I'm still getting same error, should I change any of my IDE settings or should I give you any details of my PC configuration?

**Comment by TheAlphamerc** [comment]
Which version of flutter you are using?

**Comment by rahulgurujala** [comment]
@TheAlphamerc  

> Flutter 1.19.0-4.3.pre • channel beta • https://github.com/flutter/flutter.git
> Framework • revision 8fe7655ed2 (4 weeks ago) • 2020-07-01 14:31:18 -0700
> Engine • revision 9a28c3bcf4
> Tools • Dart 2.9.0 (build 2.9.0-14.1.beta)

**Comment by TheAlphamerc** [comment]
Can you check it on `flutter 1.17.5 • channel stable` version ?

**Comment by rahulgurujala** [comment]
okay Mr. @TheAlphamerc I'm trying flutter 1.17.5. I'll let you know

**Comment by rahulgurujala** [comment]
@TheAlphamerc Sir now getting some bizarre kind of errors. I use` flutter clean` before build my app
errors as follows

> Note: C:\Users\isaac\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-0.13.7\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java uses unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> 
> 
> Note: C:\Users\isaac\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_remote_config-0.3.1\android\src\main\java\io\flutter\plugins\firebase\firebaseremoteconfig\MethodCallHandlerImpl.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> 
> 
> Note: C:\Users\isaac\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher-5.5.0\android\src\main\java\io\flutter\plugins\urllauncher\WebViewActivity.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> 
> ERROR: [TAG] Failed to resolve variable '${animal.sniffer.version}'
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:processReleaseGoogleServices'.
> > File google-services.json is missing. The Google Services Plugin cannot function without it. 
>    Searched Location: 
>   C:\Users\isaac\Downloads\flutter_twitter_clone-master\android\app\src\nullnull\google-services.json
>   C:\Users\isaac\Downloads\flutter_twitter_clone-master\android\app\src\release\google-services.json
>   C:\Users\isaac\Downloads\flutter_twitter_clone-master\android\app\src\nullnullRelease\google-services.json
>   C:\Users\isaac\Downloads\flutter_twitter_clone-master\android\app\src\nullnull\release\google-services.json
>   C:\Users\isaac\Downloads\flutter_twitter_clone-master\android\app\src\release\nullnull\google-services.json
>   C:\Users\isaac\Downloads\flutter_twitter_clone-master\android\app\google-services.json
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 2m 34s
> Running Gradle task 'assembleRelease'...                          155.5s (!)
> Gradle task assembleRelease failed with exit code 1
> Process finished with exit code 1

**Comment by TheAlphamerc** [comment]
@rahulgurujala please try solutions given at https://stackoverflow.com/questions/51797219/failed-to-resolve-variable-animal-sniffer-version-when-migrate-to-androidx

**Comment by TheAlphamerc** [comment]
@rahulgurujala Have you added` google-services.json` file and integrate firebase in app ?

**Comment by rahulgurujala** [comment]
@TheAlphamerc Thank you very much Sir. I appreciate your help for me. Yours help actually worked my app is now build.
Thank you again. Love your work.
