### ISSUE TITLE
Unread messages

### ISSUE THREAD

**Issue by Asasapatata** [TheAlphamerc/flutter_twitter_clone#69]
Hello Alpha,
Really nice project. In the chat model I see that you created the “unseen” field. Actually, when new messages are available, I do not see any difference between read and unread messages in the chatlistpage. 
How would you implement the unread/read messages feature?

**Comment by TheAlphamerc** [comment]
@Asasapatata You got it right  `unread/read` functionality is not implemented yet.
This feature can be implemented by following below steps
* When a new message sent, set `seen` value to `false` from the sender side.
* On receiver side check if the receiver message screen is in open state or not.
* If receiver chat screen is in open state then set `seen` value to `true` and update database.
* If the receiver chat screen is not in open state then wait for receiver to open chat messages. Once screen gets open check if there is `false` value of `seen` parameter is existed in `chatMessageList` or not.
* If any value found `false` then change it to `true` and update database.
