### ISSUE TITLE
getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@69874c1 W/DynamiteModule( 2692): Local module descriptor class for com.google.firebase.auth not found. W/GooglePlayServicesUtil( 2692): Google Play Store is missing.

### ISSUE THREAD

**Issue by akyunus0** [TheAlphamerc/flutter_twitter_clone#7]
I/BiChannelGoogleApi( 2692): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@69874c1
W/DynamiteModule( 2692): Local module descriptor class for com.google.firebase.auth not found.
W/GooglePlayServicesUtil( 2692): Google Play Store is missing.
I/flutter ( 2692): ****************************** error ******************************
I/flutter ( 2692): [Error] signUp PlatformException(ERROR_API_NOT_AVAILABLE, API: InternalFirebaseAuth.FIREBASE_AUTH_API is not available on this device. Connection failed with: ConnectionResult{statusCode=SERVICE_INVALID, resolution=null, message=null}, null)
I/flutter ( 2692): ****************************** error ******************************
I/flutter ( 2692): null

**Comment by akyunus0** [comment]
how can i solve this problem

**Comment by TheAlphamerc** [comment]
Can you check your Google Play Services version?

Prerequisites :
* An Android device running Google Play services 9.0.0 or later
* The Google Play services SDK from the Android SDK Manager.
* One of the reason for this problem could be, your Sign In Method inside Firebase > Auth Dashboard might be disabled.
