### ISSUE TITLE
How to remove chat section without getting errors

### ISSUE THREAD

**Issue by ChiGlobal** [TheAlphamerc/flutter_twitter_clone#70]
Hi, I'm trying to remove the chat section from the app but when I build it, I get so many malfunctions in the app, but the codes looks fine.
for example, the sidebar menu is not showing the profile picture but instead 'log in to continue' in white text...

![Screenshot_20200727-101559](https://user-images.githubusercontent.com/68472603/88539253-d0d29980-d008-11ea-9c57-682ae3c172e2.png)

and when I click on the profile page I get this
![Screenshot_20200727-101605](https://user-images.githubusercontent.com/68472603/88539301-ea73e100-d008-11ea-9c1a-378996394456.png)

please help, I think this happened because I removed the chat section😢

**Comment by TheAlphamerc** [comment]
@ChiGlobal Please try uninstalling app and install again and check if you still getting same error.

**Comment by ChiGlobal** [comment]
It worked! Thanks A Lot!! But can I still remove the chat section? without getting error?

**Comment by ChiGlobal** [comment]
And the icons, isn't there a copyright on it? Am I allowed to use those icons? @TheAlphamerc

**Comment by TheAlphamerc** [comment]
> It worked! Thanks A Lot!! But can I still remove the chat section? without getting error?

Yes, You can remove the chat section.

**Comment by TheAlphamerc** [comment]
> > It worked! Thanks A Lot!! But can I still remove the chat section? without getting error?
> 
> Yes, You can remove the chat section.

You can use those icons.

**Comment by TheAlphamerc** [comment]
> And the icons, isn't there a copyright on it? Am I allowed to use those icons? @TheAlphamerc

You can use any asset from this project.

**Comment by ChiGlobal** [comment]
thanks a lot!! this really helped me🙏
