### ISSUE TITLE
[getFCMServerKey] [Error]                     "Please configure Remote config in firebase"

### ISSUE THREAD

**Issue by The3seus** [TheAlphamerc/flutter_twitter_clone#71]
[getFCMServerKey] [Error]
"Please configure Remote config in firebase"

Everything has been configured still getting error been troubleshooting cant seem to figure why
![88760038-265a9380-d13a-11ea-9a06-757a6f5af955](https://user-images.githubusercontent.com/48400442/88760550-45a5f080-d13b-11ea-9530-a403a1eb933b.png)
![88760098-468a5280-d13a-11ea-9f85-db1df6a55182](https://user-images.githubusercontent.com/48400442/88760562-49d20e00-d13b-11ea-85ae-7c787f126ef9.png)

**Comment by teloanus** [comment]
you forget to put json before key i think

**Comment by teloanus** [comment]
json {'key blalalalsasjdalksd"}

**Comment by TheAlphamerc** [comment]
@The3seus Please check this thread :- https://github.com/TheAlphamerc/flutter_twitter_clone/issues/28#issue-611695533

**Comment by The3seus** [comment]
yes I saw that thread everything is configured but is giving me the same issue

**Comment by The3seus** [comment]
i think teloanus was right about putting json before the key seems to be working now will confirm shortly

**Comment by The3seus** [comment]
giving me a format error now FormatException (FormatException: Unexpected character (at character 1)
json {"key":"AAAA

**Comment by The3seus** [comment]
![Screenshot from 2020-07-29 14-11-55](https://user-images.githubusercontent.com/48400442/88836934-7f134600-d1a5-11ea-8cc6-227df4154416.png)

**Comment by The3seus** [comment]
nevermind seems to be working now
