### ISSUE TITLE
Can we put our tweet into some categories ?

### ISSUE THREAD

**Issue by teloanus** [TheAlphamerc/flutter_twitter_clone#72]
Hello,

I am learning so much from this project. I try to increase my skill by adding some feature. and because of that im curious to create category in our tweet.

for eg 
category [funny, politc, etc]. first when user post a tweet they must choose the category of the tweet.

then we can later sort it in the feedfage so user can see the funny tweets only.

Please teach me and give me some reference.

first of all i add,
String category in feedmodel. and after that i dont know what to do...uh.

Thank you. sorry if this is stupid request

**Comment by TheAlphamerc** [comment]
@teloanus No doubt you have asked a good question. To implement you have to follow below steps.

* on tweet compose page display a dropdown to choose user preference for tweet type.
* Dropdown should contain list of tweet type ie.  [funny, politc, etc].
Let say user selects `Funny` from the dropdown as tweet type ans submits his tweet you need to add this type to tweet model and save this tweet to firebase database.
* After fetching feed list on feed page you can add filters.

**Comment by teloanus** [comment]
Thank you sir. finally i got yr 1st point and already created it. according to the second statement. where is tweet model ? it that feedmodel.dart ?
