### ISSUE TITLE
 Flutter tried to create the file `android\settings_aar.gradle`, but failed

### ISSUE THREAD

**Issue by ChiGlobal** [TheAlphamerc/flutter_twitter_clone#73]
Hi, I just got this error... and I don't understand why it's happening..please help

![Screenshot (260)](https://user-images.githubusercontent.com/68472603/88946217-dfc67f80-d286-11ea-927b-a5323c4a76b1.png)

**Comment by TheAlphamerc** [comment]
@ChiGlobal please try with steps given in console logs. If it doesn't resolve this issue then take a fresh clone from github repo and try building again.

**Comment by ChiGlobal** [comment]
Ok... I'll try that

**Comment by ChiGlobal** [comment]
I did that, but still not working
see #76

**Comment by TheAlphamerc** [comment]
@ChiGlobal which version of flutter you are using?

**Comment by ChiGlobal** [comment]
@TheAlphamerc don't worry, I've been able to fix it.. turns out that I hadn't migrated to Android x yet... When I did that .it was solved and some other things like resource linking ... And I'm using the latest version of Flutter v.1.17.5
