### ISSUE TITLE
where did these hex codes for these icons come from? 

### ISSUE THREAD

**Issue by The3seus** [TheAlphamerc/flutter_twitter_clone#74]
I see you have an APPicon class 
class AppIcon{
static final int fabTweet = 0xf029;
static final int messageEmpty = 0xf187

Where did you get the hex to these icons im trying to add additional icons but cannot seem to find the correct one.  I found this but useless https://github.com/google/material-design-icons/blob/master/iconfont/codepoints any help? Thanks

**Comment by TheAlphamerc** [comment]
There is an icon font file in the assets folder. The hex code for icons is taken from icons available in icon font file.
To find out more detail [Click Here](https://www.woolha.com/tutorials/flutter-create-custom-icon)
<img width="318" alt="Screenshot 2020-07-31 at 10 07 08 AM" src="https://user-images.githubusercontent.com/37103237/89000723-b1dc4c00-d315-11ea-824f-6d81ccc076db.png">

**Comment by TheAlphamerc** [comment]
@The3seus Closing this thread for now if you have question related to icons feel free to reopen the issue.
