### ISSUE TITLE
status bar

### ISSUE THREAD

**Issue by emiravdovic** [TheAlphamerc/flutter_twitter_clone#77]
How to the set status bar color, or where I can change ?
Thanks.. 👍

**Comment by TheAlphamerc** [comment]
1. Import below package
``` dart 
import 'package:flutter/services.dart';
```
2. Add below code in `initState()` methods in any screen to update the status bar color 
```dart
      SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle(
          systemNavigationBarColor: Color(0xffffffff), // navigation bar color
          statusBarColor: Colors.white, // status bar color
          statusBarIconBrightness: Brightness.dark));
```

**Comment by emiravdovic** [comment]
@TheAlphamerc  can we change also botom navigation bar in android, to be same color like pages..

![android-pie-navigation-bars-christian-ghanime](https://user-images.githubusercontent.com/53181006/89575412-0314a000-d82e-11ea-8e87-7aed8162f61b.png)

**Comment by TheAlphamerc** [comment]
> 1. Import below package
> 
> ```dart
> import 'package:flutter/services.dart';
> ```
> 
> 1. Add below code in `initState()` methods in any screen to update the status bar color
> 
> ```dart
>       SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle(
>           systemNavigationBarColor: Color(0xffffffff), // navigation bar color
>           statusBarColor: Colors.white, // status bar color
>           statusBarIconBrightness: Brightness.dark));
> ```

@emiravdovic below paremeter is responsible for change bottom navigation bar color
``` dart
  systemNavigationBarColor: Color(0xffffffff), 
```
