### ISSUE TITLE
How to hide @ from users in feed page.

### ISSUE THREAD

**Issue by emiravdovic** [TheAlphamerc/flutter_twitter_clone#78]
can we make that @ is not visible in feed page, and that we can tag user after this

**Comment by TheAlphamerc** [comment]
@emiravdovic tag user in tweets functionality is available. You can tag any user while creating tweets.
I didn't understand why you still want to remove `@` tag?

**Comment by emiravdovic** [comment]
@TheAlphamerc I don't want to remove tag option, I just want to remove @ form feed page, to userName be without @

@userName (x)    @emiravdovic 
userName  (✓)     emiravdovic

**Comment by emiravdovic** [comment]
@TheAlphamerc I mean how that when user create profile to not have @, to look like displayName but to be userName.
When somebody come in my profile for example and I don't want to show there my displayName, I want to there have just userName but I want to this username be without @, hope you understand.

**Comment by TheAlphamerc** [comment]
@emiravdovic `@` tag is assoiciated with username and it is saved in db. You can remove it by using `substring()` method on username.

<img width="835" alt="Screenshot 2020-08-07 at 7 05 04 PM" src="https://user-images.githubusercontent.com/37103237/89651101-0321a800-d8e1-11ea-8dea-11c0e41abd13.png">

To remove `@` from profile screen add substring method on https://github.com/TheAlphamerc/flutter_twitter_clone/blob/2bd6d493da52e90a697ab8514bcfee722a941a12/lib/page/profile/profilePage.dart#L504

Use below code to remove `@` tag from profile page.

```dart
    Padding(
          padding: EdgeInsets.symmetric(horizontal: 9),
          child: customText(
            '${user.userName.substring(1,user.userName.length)}',
            style: subtitleStyle.copyWith(fontSize: 13),
          ),
        ),
```
