### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by mauro16** [TheAlphamerc/flutter_twitter_clone#79]
thanks for share, very nice from you..
i would like to know how can i show the icons on app?
for me just show something like this [x], thanks.
where is the icons?(:

class AppIcon {
  static final int fabTweet = 0xf029; //  only colors? 
  static final int messageEmpty = 0xf187;
  static final int messageFill = 0xf554;
  static final int search = 0xf058;
}

**Comment by TheAlphamerc** [comment]
@mauro16 please check this thread https://github.com/TheAlphamerc/flutter_twitter_clone/issues/74#issuecomment-666915166

**Comment by mauro16** [comment]
Thanks for your attention 🙂

**Comment by ChiGlobal** [comment]
> @mauro16 please check this thread [#74 (comment)](https://github.com/TheAlphamerc/flutter_twitter_clone/issues/74#issuecomment-666915166)

I checked it but I didn't find the solution
