### ISSUE TITLE
Admin

### ISSUE THREAD

**Issue by tekinc** [TheAlphamerc/flutter_twitter_clone#8]
Have you developed a backend admin for this app?

**Comment by TheAlphamerc** [comment]
Firebase is used for backend. No admin panel is created yet.

**Comment by ferrumzp** [comment]
Hello. I want to make admin panel for this app. Can you help me? 
I add field called "**role**" in Cloud Firestore. But what will be next - don't know.
My code in **AuthState.dart**
`  //get Logged in user role
getRole(BuildContext context) async {
  user = await _firebaseAuth.currentUser();
  kfirestore
      .collection(USERS_COLLECTION)
      .document(userId)
      .get()
      .then((documentSnapshot) {
    if (documentSnapshot.data['role'] == 'admin') {
    Navigator.push(context, MaterialPageRoute(builder: (BuildContext context)=>AdminPage()));}
  }).catchError((error) {});
}
`
Can you help?

**Comment by TheAlphamerc** [comment]
You want to create admin panel in app ? if yes then I suggest you to go for web admin panel.

**Comment by ferrumzp** [comment]
No. I want to create auth by user role and dashboard with admin function CRUD etc

**Comment by pinkasey** [comment]
> No. I want to create auth by user role and dashboard with admin function CRUD etc..
> But I can’t understand how to correctly write a method for checking user roles.
> I learnig flutter for 3 months and my knowledge is really poor

Excuse me for barging in,
I'm also new to Flutter and Firebase,
but I think you need to look for your answers in Firebase documentation.

**Comment by TheAlphamerc** [comment]
It's been a long time since this issue is created, now it seems like I have no future plans to create a web admin panel for this project so closing this issue for now. If anyone interested in creating an admin panel and wants to contribute to this project feel free to open this issue again.
