### ISSUE TITLE
Icons not showing properly

### ISSUE THREAD

**Issue by ChiGlobal** [TheAlphamerc/flutter_twitter_clone#81]
Hi, the app has been working perfectly but I built it and now it's having problems. 

![Screenshot_20200809-150214.png](https://user-images.githubusercontent.com/68472603/89735340-bad9c580-da59-11ea-9697-9da8e442f13e.png)

I can't see the icons, please help🙏🏼

**Comment by TheAlphamerc** [comment]
@ChiGlobal have you changed icons in bottom navigation bar?

**Comment by ChiGlobal** [comment]
@TheAlphamerc no I didn't, I had to create a new project..now it's working. But I came across something else... When I change the profile picture...it doesn't show on all posts only new posts.. and the people I followed will be gone, I had to unfollow and refollow before their posts came back..
See👇🏼
![Screenshot_20200810-151814.png](https://user-images.githubusercontent.com/68472603/89799686-b549b180-db25-11ea-82f4-38233ad1f5de.png)

**Comment by ChiGlobal** [comment]
@TheAlphamerc and please is it possible for the app to send notifications when the app is not running?

**Comment by TheAlphamerc** [comment]
> @TheAlphamerc no I didn't, I had to create a new project..now it's working. But I came across something else... When I change the profile picture...it doesn't show on all posts only new posts.. and the people I followed will be gone, I had to unfollow and refollow before their posts came back..
> See👇🏼
> ![Screenshot_20200810-151814.png](https://user-images.githubusercontent.com/68472603/89799686-b549b180-db25-11ea-82f4-38233ad1f5de.png)

@ChiGlobal profile pic issue is a known issue check https://github.com/TheAlphamerc/flutter_twitter_clone/issues/80#issue-675077107

If you are using some other icons which is not available in icons.ttf file then below customIcon widget for it.
``` dart
customIcon(context,icon:AppIcon.homeFill,size: 22, istwitterIcon: true, isEnable: false) 
```

if you are using icon which is not available in icons.ttf file use below code:-
``` dart
Icon(Icons:Icons.access_alarm, color: Theme.of(context).primaryColor  ),
```

**Comment by ChiGlobal** [comment]
@TheAlphamerc ok thanks, please what about the notifications? Is there a way that I can trigger notifications when someone sends a message.. like for example, I want to add live stream to the app, and I want to let the users know when the host is live with notifications

**Comment by ChiGlobal** [comment]
@TheAlphamerc Hi, please where can I find the code to correct... I tried looking for it but I can't find it 🙏🏼

**Comment by TheAlphamerc** [comment]
> @TheAlphamerc Hi, please where can I find the code to correct... I tried looking for it but I can't find it 🙏🏼

@ChiGlobal talking about bottom navigation bar icons code ?

**Comment by ChiGlobal** [comment]
@TheAlphamerc no, I'm talking about the profile pic issue that you referred me to, where in the app can I make the changes of fetching user data

**Comment by TheAlphamerc** [comment]
@ChiGlobal For now I have a workaround to resolve this bug. Please check it here:- https://github.com/TheAlphamerc/flutter_twitter_clone/issues/80#issuecomment-672572634
