### ISSUE TITLE
Search bar

### ISSUE THREAD

**Issue by ifiy** [TheAlphamerc/flutter_twitter_clone#82]
Please , how can I make the search bar to search for the profiles instead of it being listed? And also, please how can I implement the dark mode function such that it works?

**Comment by ifiy** [comment]
Please, this is urgent!

**Comment by TheAlphamerc** [comment]
Just hide the users list and show user's according to the search query.
To implement dark mode create Light and dark theme and use Theme.of(context) to initialise the colors to every widget.

**Comment by TheAlphamerc** [comment]
Check https://github.com/TheAlphamerc/flutter_news_app project to get an idea about implement dark mode

**Comment by ifiy** [comment]
> 
> 
> Just hide the users list and show user's according to the search query.
> To implement dark mode create Light and dark theme and use Theme.of(context) to initialise the colors to every widget.

I don't understand for the reply to the search bar

**Comment by ifiy** [comment]
Also pls how do you allow users to change the cover picture?

**Comment by TheAlphamerc** [comment]
Update cover picture functionality is not developed yet. If you want to implement it then follow same procedure that we following in updating the profile picture.

**Comment by ifiy** [comment]
Please sir, can you explain the search bar solution for me?

**Comment by ifiy** [comment]
I tried what you said for the search bar but it did not work

**Comment by TheAlphamerc** [comment]
@ifiy At initial when search screen open up just hide the user's list and when user type in search bar to search a user at this moment display list of users.

**Comment by ifiy** [comment]
![Screenshot (275)_1](https://user-images.githubusercontent.com/58063973/90730834-b2d31e80-e2c0-11ea-8179-221bb9095014.png)

**Comment by TheAlphamerc** [comment]
@ifiy update initState method with following code

```dart
 @override
  void initState() {
    WidgetsBinding.instance.addPostFrameCallback((_) {
      final state = Provider.of<SearchState>(context);
      state.filterByUsername("********");
      // state.resetFilterList();
    });
    super.initState();
  }
```

<img width="1678" alt="Screenshot 2020-08-20 at 2 37 47 PM" src="https://user-images.githubusercontent.com/37103237/90750750-e169ed00-e2f2-11ea-8afc-bd4c9ba81a1e.png">
