### ISSUE TITLE
Deleted users Error

### ISSUE THREAD

**Issue by emiravdovic** [TheAlphamerc/flutter_twitter_clone#83]
I have problem if I delete some users from firebase, and this users before created a comment or message, after this if I open this comment or message or ect. This showing errors.. How to we create that if we delete user from database this automatically remove all posts or comments of this users from app. 

![IMG_6681](https://user-images.githubusercontent.com/53181006/90025520-772fc780-dcb6-11ea-8956-04e974c8c9b5.jpeg)

**Comment by TheAlphamerc** [comment]
@emiravdovic If you delete any user from the database manually then you also have to delete his tweets and comments manually from the database.

**Comment by emiravdovic** [comment]
@TheAlphamerc I understand this, but can we make that this automaticly remove all data from database if I just delete user profile.. bc maybe in future if somebody want to remove some user profile wich is fake and have lot of spam post and message, after I delete like this all user with the user sended message or comment something will have this error..

**Comment by TheAlphamerc** [comment]
@emiravdovic Instead of deleting such user implement block or disable user functionality. The functionality which you are asking is not a part of the app. This functionality is a part of the admin panel and unfortunately, we didn't have this right now.

**Comment by emiravdovic** [comment]
@TheAlphamerc I understand, will be soon implemented admin panel?

**Comment by TheAlphamerc** [comment]
@emiravdovic Currently I have no plan for this.
