### ISSUE TITLE
Notification removed

### ISSUE THREAD

**Issue by ChiGlobal** [TheAlphamerc/flutter_twitter_clone#84]
Hi, please why does it keep removing the notifications?
![Screenshot (291).png](https://user-images.githubusercontent.com/68472603/90148661-79a82500-dd7b-11ea-83ab-02c0ac3a5b61.png)

**Comment by TheAlphamerc** [comment]
@ChiGlobal If your tweets have no likes initially and then you or other users add a like then you will get a notification on notification section. If the same user undo his like then again tweets like sets to zero and the notification which you got will be deleted.

**Comment by ChiGlobal** [comment]
@TheAlphamerc but that didn't happen, I liked a tweet of mine, then *notification added* appeared... when I clicked on notifications then it said *notification removed*

**Comment by ChiGlobal** [comment]
@TheAlphamerc fcm server key error
![Screenshot (294)](https://user-images.githubusercontent.com/68472603/90163624-402ce500-dd8e-11ea-920e-5fd4a152ec0b.png)
![Uploading Screenshot (295).png…]()

**Comment by emiravdovic** [comment]
> @TheAlphamerc fcm server key error
> ![Screenshot (294)](https://user-images.githubusercontent.com/68472603/90163624-402ce500-dd8e-11ea-920e-5fd4a152ec0b.png)
> ![Screenshot (295)](https://user-images.githubusercontent.com/68472603/90164578-7f0f6a80-dd8f-11ea-8541-e131eaa805f4.png)

Follow this steps from the page and you will fix it.

https://github.com/TheAlphamerc/flutter_twitter_clone/wiki/Gettings-Started

**Comment by ChiGlobal** [comment]
@emiravdovic oh wow, do I have to create a new server key for each app?

**Comment by TheAlphamerc** [comment]
@ChiGlobal If you are using the same firebase project in new app then you can use same server key.

**Comment by ChiGlobal** [comment]
@TheAlphamerc ok thanks🙏🏼
