### ISSUE TITLE
What to Tweet

### ISSUE THREAD

**Issue by ifiy** [TheAlphamerc/flutter_twitter_clone#88]
Hi. Please if I want to restrict what a user tweets to a particular topic, what do I do?

**Comment by TheAlphamerc** [comment]
@ifiy You can't restrict the user to tweet. Users can tweet about anything.

**Comment by ifiy** [comment]
I am trying to add a unique aspect and I am limiting the app such that it will only be for chefs and bakers

**Comment by emiravdovic** [comment]
@TheAlphamerc  Maybe  to use Firebase ML Kit image recognition ?

**Comment by TheAlphamerc** [comment]
@emiravdovic ML kit image recognition will only work for images so it is not an option. @ifiy What about displaying a note description to user before creating a tweet?. Note description can be like "Please create your tweet relevant to Meals.

**Comment by emiravdovic** [comment]
@TheAlphamerc I think that ML Kit can recognise text also..
 https://developers.google.com/ml-kit

**Comment by TheAlphamerc** [comment]
@ifiy you can have a look at it.

**Comment by ifiy** [comment]
> 
> 
> @TheAlphamerc I think that ML Kit can recognise text also..
> https://developers.google.com/ml-kit

The text recognition is also for images. It is pick text from images

**Comment by TheAlphamerc** [comment]
> Hi. Please if I want to restrict what a user tweets to a particular topic, what do I do?

Can you share a reference example app having such functionality?

**Comment by ifiy** [comment]
I don't know whether there is a reference app

**Comment by TheAlphamerc** [comment]
@ifiy we can't proceed with this thread until we have sufficient information.
