### ISSUE TITLE
Wrong followers displayed on back button pressed

### ISSUE THREAD

**Issue by nonybrighto** [TheAlphamerc/flutter_twitter_clone#89]
**Describe the bug**
When viewing a user's followers and then the followers of one of his/her followers, the list displays the last gotten followers on back button pressed instead of going back to the original list.

**To Reproduce**
1. Go to the profile of user A with followers.
2. Click on followers to view the list of user A's followers.
3. Click on user B, a follower of user A to view his/her profile.
4. Click on followers to view the list of user B's followers.
5. Press the back button twice. to the page that is meant to display user A's followers. It will still display user B's followers.

**Expected behavior**
Expects list to show user A's followers on back button pressed but it shows the last gotten follower list.

**Comment by TheAlphamerc** [comment]
@nonybrighto Please let me know on which branch you found this issue?

**Comment by OptlocDev** [comment]
dont know why but I noticed in the user model this line was missing. 

this.followingList

**Comment by dubey2k** [comment]
Is it fixed?

**Comment by TheAlphamerc** [comment]
Issue is fixed.
