### ISSUE TITLE
Don't work on real iOS device, while on simulator work good..

### ISSUE THREAD

**Issue by avdoviic** [TheAlphamerc/flutter_twitter_clone#9]
I have problem, when flutter run app on iOS simulator app work without problems, but when I run on real device application crash und can't open.. und also for some reason login with google stoped to work..  Thanks, Great work!!

**Comment by TheAlphamerc** [comment]
It seems like you are using an incorrect provision profile. Please check if you have added your phone UDID in the provisioning profile or not.

**Comment by avdoviic** [comment]
> It seems like you are using an incorrect provision profile. Please check if you have added your phone UDID in the provisioning profile or not.

Im not realy  shure how to check this..

**Comment by TheAlphamerc** [comment]
In order to run app on the iOS device, you need apple developer account. You can create and download provision profile from there. Check apple documentation :- https://help.apple.com/xcode/mac/current/#/dev154b28f09

**Comment by avdoviic** [comment]
> In order to run app on the iOS device, you need apple developer account. You can create and download provision profile from there. Check apple documentation :- https://help.apple.com/xcode/mac/current/#/dev154b28f09

I'm fixed this , the problem was on my iOS version 13.3.1,  after upgrade on the last version the problem was gone.. Thank you very much, und keep upgrading app is amazing.

**Comment by TheAlphamerc** [comment]
Your feedback is much appreciated. Thanks for your interest in `Fwitter` project.
