### ISSUE TITLE
direct messages

### ISSUE THREAD

**Issue by OptlocDev** [TheAlphamerc/flutter_twitter_clone#91]
The inability to block users or delete messages related to direct messages,
either on longPress or a slide ui function that would either open the bottom sheet or a modal and give the option to delete messages.

I see you have the options there for display within conversation info, but I would like to put method/functions with whats showing on the UI. I am willing to work with you if you want

**Comment by TheAlphamerc** [comment]
@OptlocDev The functionality that you are talking about has not been developed yet, I will glad if you can work on these features and help me to implement them.

**Comment by OptlocDev** [comment]
I will see what I can come up with. You can close this thread.
