### ISSUE TITLE
I cant Build apk 

### ISSUE THREAD

**Issue by karambitmonger** [TheAlphamerc/flutter_twitter_clone#92]
Hi there,i am able t deploy the app to my phone without any problem but i cant be able to build an apk.i get this error:

Execution failed for task ':app:compileFlutterBuildRelease'. finished with non-zero exit value 1 

I am using vs code

**Comment by TheAlphamerc** [comment]
@karambitmonger please share console error logs

**Comment by karambitmonger** [comment]
found a work around. The error was due to treeshake icons.fixed it
