### ISSUE TITLE
Cant recieve push notifications on any device

### ISSUE THREAD

**Issue by karambitmonger** [TheAlphamerc/flutter_twitter_clone#93]
I am unable to receive any push notification. Can you please tell me how to implement it?

**Comment by TheAlphamerc** [comment]
@karambitmonger Have you followed all instructions given at [Wiki](https://github.com/TheAlphamerc/flutter_twitter_clone/wiki)

**Comment by karambitmonger** [comment]
I skipped the SHA1 part of it because i wasnt using google sign in,could this be the reason?

**Comment by rish07** [comment]
@karambitmonger yes, SHA1 might be the reason for it. I did the SHA1 and am receiving notifications.

**Comment by TheAlphamerc** [comment]
@karambitmonger please have a look on  https://github.com/TheAlphamerc/flutter_twitter_clone/issues/28#issue-611695533 and make sure you have configured firebase remote configure correctly

**Comment by karambitmonger** [comment]
Still unable to receive push notifications even after following the instructions,its been 3 weeks of trying and nothing.

**Comment by TheAlphamerc** [comment]
@karambitmonger If you still not able to send push then first try to send notification using postman. If you able to send notification through postman then it will confirm that you are using the correct FCM server key and firebase token.
See this [Send notification using postman](https://medium.com/android-school/test-fcm-notification-with-postman-f91ba08aacc3)
