### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by emiravdovic** [TheAlphamerc/flutter_twitter_clone#94]
"Add option for user to remove comments from other users on his posts"

that he can remove comments from posts if we don't like , bc now this we can make only over database or to ask user to remove comment what is crazy :)

**Comment by TheAlphamerc** [comment]
@emiravdovic can we do the same on twitter?

**Comment by emiravdovic** [comment]
> @emiravdovic can we do the same on twitter?

Actually I don't know, I just thinked that is good option to have..

**Comment by emiravdovic** [comment]
@TheAlphamerc  how can I add this option? Thanks..

**Comment by TheAlphamerc** [comment]
@emiravdovic check the code where Tweet owner can delete his tweet. You just need to follow those steps but now this time allows this permission to tweet owner.

**Comment by emiravdovic** [comment]
@TheAlphamerc  where I can find this code?

**Comment by TheAlphamerc** [comment]
To delete a tweet there is a method `deleteTweet` available in [FeedState](https://github.com/TheAlphamerc/flutter_twitter_clone/blob/master/lib/state/feedState.dart)
<Br>

<img width="752" alt="Screenshot 2020-09-03 at 10 11 07 AM" src="https://user-images.githubusercontent.com/37103237/92071983-cbb5f680-edcd-11ea-86c7-09e528ac3cd5.png">
