### ISSUE TITLE
Awesome Work Bro!

### ISSUE THREAD

**Issue by Ausyys** [TheAlphamerc/flutter_twitter_clone#95]
Hi @TheAlphamerc , I love your work! You really did a great job👏👏
But I wanna try and add something and I need your help

I'm kinda new to flutter but I understand a little of it, so I want to add a live stream (Agora) to the app but the UI I'm using for the live stream wrote their sign up screen totally different from yours and it is giving me some hard time... 

so, in the UI they used a widget called `SharedPreferences()` and on their home page they called a function to retrieve some data from the sign up page:
![Screenshot (321)](https://user-images.githubusercontent.com/70477317/91661645-4a144f00-ead5-11ea-8ff1-ed54ca8777c9.png)

so I compared theirs to yours and found out that I had to ask for help, how am I going to use the `SharedPreferences()` function in your sign up page and will it affect the code? Or should I use firestore?

Thanks once again for the awesome code, peace👍

**Comment by TheAlphamerc** [comment]
Hi @Ausyys , Thanks for your appreciation. First of all let me tell you the `SharedPreferences()` is not a widget it is a method provided by  [SharedPreferences](https://pub.dev/packages/shared_preferences) plugin which store data in the form of key-value pair locally.
The `loadSharePref()` in screenshot is just initilising the `displayName` and `image` parameter here.
I guess after signup/signin they are getting these data from api response and stored in local using `SharedPreferences()` plugin and on home page to display username and images they have used `loadSharePref()`  method.

**Comment by Ausyys** [comment]
@TheAlphamerc wow, great to know. So can I use firestore to get the `displayName` and `image` from the signup and use it at the home page?

**Comment by Ausyys** [comment]
> Hi @Ausyys , Thanks for your appreciation.
you're welcome👍

**Comment by TheAlphamerc** [comment]
Yes, you can use Firestore.

**Comment by Ausyys** [comment]
ok, thanks a lot🙏

**Comment by Ausyys** [comment]
Hi @TheAlphamerc , I got an error saying `_FeedPageState.loadSharedPref.<anonymous closure>` and I wanted to know if I wrote this well:

```
void loadSharedPref() {
    setState(() {
      displayName = FireStoreClass.getName() ?? '';
      image = FireStoreClass.getImage() ??
          'https://nichemodels.co/wp-content/uploads/2019/03/user-dummy-pic.png';
    });
  }
```
the `FireStoreClass()` :
```
FireStoreClass{
\\above code
 static Future<String> getName({displayName}) async {
    final snapShot =
        await _db.collection(userCollection).document(displayName).get();
    return snapShot.data['displayName'];
  }
 static Future<String> getImage({displayName}) async {
    final snapShot =
        await _db.collection(userCollection).document(displayName).get();
    return snapShot.data['image'];
  }
\\below code
}
```
thanks for the help🙏

**Comment by Ausyys** [comment]
u there? @TheAlphamerc

**Comment by TheAlphamerc** [comment]
> Hi @TheAlphamerc , I got an error saying `_FeedPageState.loadSharedPref.<anonymous closure>` and I wanted to know if I wrote this well:
> 
> ```
> void loadSharedPref() {
>     setState(() {
>       displayName = FireStoreClass.getName() ?? '';
>       image = FireStoreClass.getImage() ??
>           'https://nichemodels.co/wp-content/uploads/2019/03/user-dummy-pic.png';
>     });
>   }
> ```
> the `FireStoreClass()` :
> ```
> FireStoreClass{
> \\above code
>  static Future<String> getName({displayName}) async {
>     final snapShot =
>         await _db.collection(userCollection).document(displayName).get();
>     return snapShot.data['displayName'];
>   }
>  static Future<String> getImage({displayName}) async {
>     final snapShot =
>         await _db.collection(userCollection).document(displayName).get();
>     return snapShot.data['image'];
>   }
> \\below code
> }
> ```
> 
> screenshot:
> ![Screenshot (327)](https://user-images.githubusercontent.com/70477317/91727800-17805a00-eb9a-11ea-9e8e-38d0f366a6c2.png)
> 
> thanks for the help🙏

You're doing it correct but you are getting null data in `snapShot.data['displayName']`. Please check if you have data at same location in Firestore.

**Comment by Ausyys** [comment]
oh ok, I actually do not have it there but I tried adding in `authState`:
![Screenshot (329)](https://user-images.githubusercontent.com/70477317/91735146-c5dccd00-eba3-11ea-8883-228d0e6312a8.png)

to be uploaded to firestore. I this correct too?

**Comment by Ausyys** [comment]
But is there a way that I can print out the error instead of getting it on the app?

**Comment by TheAlphamerc** [comment]
@Ausyys Yes, it seems like you are on right track

**Comment by Ausyys** [comment]
Hi @TheAlphamerc , I've been able to fix it. Thanks a lot. But I noticed something on the search page, here take a look:
![Screenshot_20200903-165000](https://user-images.githubusercontent.com/70477317/92144762-14da6a80-ee0f-11ea-92cc-243442a9fca9.png)
the user profilePic is not showing on the search page

**Comment by Ausyys** [comment]
Hi @TheAlphamerc , it's working now.. but there's a bug whenever I want to follow another user... It's not working at all

**Comment by TheAlphamerc** [comment]
@Ausyys Have you modified original code

**Comment by Ausyys** [comment]
@TheAlphamerc yeah, but not the follow... I only changed the colors to dark grey [900]. And I  removed the settings icon at the top there because none of the functions were working.

**Comment by TheAlphamerc** [comment]
@Ausyys on which branch you are working? Are you getting any error on console when you click on the follow button?

**Comment by Ausyys** [comment]
I'll debug that and check, what do you mean by branch? @TheAlphamerc

**Comment by TheAlphamerc** [comment]
@Ausyys This project has 4 git branches, I am asking on which git branch you are working.

**Comment by Ausyys** [comment]
@TheAlphamerc I'm using the master branch
