### ISSUE TITLE
Search bar

### ISSUE THREAD

**Issue by ifiy** [TheAlphamerc/flutter_twitter_clone#96]
The search bar code from before is not working. It is now affecting the feed page

**Comment by TheAlphamerc** [comment]
I didn't understand what you are saying, Can you explain in detail ?

**Comment by ifiy** [comment]
The code that was shown earlier is not working. The search bar is still not working

**Comment by TheAlphamerc** [comment]
The search bar is working fine I have checked twice. Make sure you are working with latest code.
