### ISSUE TITLE
Image and document sharing in chat feature

### ISSUE THREAD

**Issue by karambitmonger** [TheAlphamerc/flutter_twitter_clone#97]
Has anyone tried to implement the image and document sharing capabilities in the app? i have some experience in android development and a few months in flutter.

**Comment by TheAlphamerc** [comment]
Feature haven't developed yet but its workaround can be found  here -> https://github.com/TheAlphamerc/flutter_twitter_clone/issues/170

**Comment by shuaibidshuaib** [comment]
> 
> 
> Has anyone tried to implement the image and document sharing capabilities in the app? i have some experience in android development and a few months in flutter.

pls sir alphamerc , explain to me the section to apply this code, i want my app also to have this feature, im still  new to flutter, but doing this sort of things help me to get better, pls sir show me the page to apply the code, so that my users can send images via chat, pls help.

**Comment by TheAlphamerc** [comment]
> Feature haven't developed yet but its workaround can be found here -> #170

@shuaibidshuaib the solution is given in #170 thread refer to below code https://github.com/TheAlphamerc/flutter_twitter_clone/blob/e6edd6e9b0850d4bdf541bc19f97dba053358ea7/lib/ui/page/message/chatScreenPage.dart#L217

Just replace the `submitMessage` method code with the new code provided in the solution.

**Comment by shuaibidshuaib** [comment]
ok thank you very much sir, i now understand.
