### ISSUE TITLE
Realtime database Rules

### ISSUE THREAD

**Issue by Asasapatata** [TheAlphamerc/flutter_twitter_clone#98]
Hello,
Nice work, congratulations!

Since it is not mentioned, I was wondering if you set rules for the database. Is the database running with the default rules provided by Firebase? Or did you implement some security rules?

It would be great to give a glance to that, don't you think?

Thanks!

**Comment by TheAlphamerc** [comment]
Hi @Asasapatata, I haven't added any additional dB rules yet. It is running with default rules.
Do you think it will be good or beneficial to add extra security rules?

**Comment by uzairpawaskar** [comment]
can this issue be related to mine where i cannot see every user's tweet on home page
i am just seeing the uploaded one not from the other users

**Comment by aligorithm** [comment]
The security rules aren't defined on the client (app) side. They're defined on the console. Without the rules, anyone with the link can essentially read, write, modify or delete any or all data on the database, with relative ease.

I'm trying to come up with a way to implement the security rules that allow the app to be used without compromising security.

**Comment by TheAlphamerc** [comment]
@aligorithm can you share with us what you come up with ?

**Comment by aligorithm** [comment]
Sure, I will!
