### ISSUE TITLE
Creating a video image player page

### ISSUE THREAD

**Issue by karambitmonger** [TheAlphamerc/flutter_twitter_clone#99]
![Screenshot from 2020-09-30 18-49-10](https://user-images.githubusercontent.com/70143156/94708899-c5278a00-034d-11eb-8c7d-016fb5270146.png)
Hi guys,i have added two new items on the post structure,type and videoURL. I will add this data manually from the firebase backend. I need help rerouting the post when clicked to a video player page which will play the videoUrl i placed in the firebase backend. I need help carrying the videoURL data while navigating to the video player page. The videoUrl is ayoutube URL so i need help with code that will help me play that videoUrl

**Comment by TheAlphamerc** [comment]
@karambitmonger have you tried [Youtube player flutter](https://pub.dev/packages/youtube_player_flutter) plugin to play youtube video?

**Comment by karambitmonger** [comment]
I have but how do i carry the videoUrl from feed model to the page where the video is to be played? can you share some code for that?

**Comment by TheAlphamerc** [comment]
You can pass Feedmodel while navigating in video play constructor.

**Comment by karambitmonger** [comment]
@TheAlphamerc some code would really help

**Comment by TheAlphamerc** [comment]
@karambitmonger I can't help you with code. You have to figure it out by yourself.

**Comment by JavierPerezLavadie** [comment]
Hello karambitmonger , did you manage to add the video functionality? I would like to know how you did. Thanks
